### ISSUE TITLE
Contrast of selection highlight in sidebar forms to low

### ISSUE THREAD

**Issue by hellp** [sdras/night-owl-vscode-theme#10]
I often `Ctrl+Shift+F` to search globally. I take the selection highlight as a cue to see that I have focused the search form successfully.

In Night Owl the selection is barely visible:
![screenshot-20180518-01caf0](https://user-images.githubusercontent.com/32779/40223247-b0a6e088-5a82-11e8-9cd2-7a7b62511943.png)

Compare this to Code’s Dark theme:
![screenshot-20180518-01ef9a](https://user-images.githubusercontent.com/32779/40223254-b4de9b78-5a82-11e8-81dd-a540c91a7de0.png)

Other than that I like the theme, so thank you :)

**Comment by sdras** [comment]
Ah yeah I see what you mean. I'll get that fixed up, I didn't know people were using it that heavily. Thanks!

**Comment by lauragift21** [comment]
If this is still open I'd love to take it on.

**Comment by sdras** [comment]
That would be much appreciated, @lauragift21!

**Comment by sdras** [comment]
closed thanks to @lauragift21!
