### ISSUE TITLE
More italics

### ISSUE THREAD

**Issue by bsvipas** [sdras/night-owl-vscode-theme#103]
What about more italics?

`get`
`set`
`function`
`this`
`super`
`const`
`let`
`var`
`Promise`
`Map`
`console`
`__filename`
`__dirname`
`class`
`interface`
`type`
`extends`
`enum`
`export`
`export default`
`module`
`if`
`else if`
`switch`
`case`
`return`
`break`
`continue`
`while`
`for`
`for...in`
`for...of`
`while...do`
`await`
`async`
`try/catch/finally`
`throw`
`declare`
`namespace`
`arguments`

**Comment by bsvipas** [comment]
If needed I can create PR.

/cc @sdras

**Comment by sdras** [comment]
No, if you go through the changelog you can see that I was fairly aggressive with the italics at first but after a lot of feedback and also working with the theme myself, I decided to bring the usage down. If you want, can always customize the theme (instructions in the readme), or another theme might suit you better.

**Comment by bsvipas** [comment]
@sdras But just for the curiosity why then you keep some keywords italic? It looks a little bit weird then `class` is non-italic and `extends` is italic. But maybe it just for me. And with such amazing font like Dank Mono italic look amazing :smile:
