### ISSUE TITLE
get/set in JS/TS

### ISSUE THREAD

**Issue by bsvipas** [sdras/night-owl-vscode-theme#104]
![image](https://user-images.githubusercontent.com/30043375/41963067-564c4604-79ff-11e8-9a4b-81a7433be77b.png)

As you can see it should be the same as `static`, talking about color and italic.

**Comment by bsvipas** [comment]
If needed I can create a PR.

/cc @sdras

**Comment by sdras** [comment]
Yeah, this is a spot where it makes sense to make them the same, I would accept a PR for this, thank you!

**Comment by bsvipas** [comment]
Okay. I will create a PR today :sparkles:

**Comment by bsvipas** [comment]
@sdras PR already opened: https://github.com/sdras/night-owl-vscode-theme/pull/110 :fire:

**Comment by sdras** [comment]
Thanks!
