### ISSUE TITLE
switch/case coloring

### ISSUE THREAD

**Issue by bsvipas** [sdras/night-owl-vscode-theme#105]
Shouldn't `switch/case` be the same color as `if/else/elseif`?

![image](https://user-images.githubusercontent.com/30043375/41964228-270e9ee8-7a02-11e8-9fca-fb0099f2f622.png)

**Comment by bsvipas** [comment]
If needed I can create a PR.

/cc @sdras

**Comment by sdras** [comment]
I actually went back and forth on this one and this is what I settled on, with the break and function keywords I wanted more contrast and someone else remarked that it was too similar/too much italic. I think it's good as is now.

**Comment by bsvipas** [comment]
@sdras Maybe you're right, it makes sense to separate it since it can be messy with a lot of LOC.
