### ISSUE TITLE
function coloring

### ISSUE THREAD

**Issue by bsvipas** [sdras/night-owl-vscode-theme#106]
Isn't `function` suppose to be as other `control` keywords to be consistent?

![image](https://user-images.githubusercontent.com/30043375/41964624-274f627e-7a03-11e8-9e2d-b955b2fbd5f3.png)

Same goes for `switch/case`, but I already opened an issue for that too.

**Comment by bsvipas** [comment]
If needed I can open a PR.

/cc @sdras

**Comment by sdras** [comment]
no, these are intentionally set apart, please see article in other issue for more info, thank you

**Comment by bsvipas** [comment]
@sdras Right now I understand why, to separate things which improves readability.
