### ISSUE TITLE
String template literals in JS/TS/???

### ISSUE THREAD

**Issue by bsvipas** [sdras/night-owl-vscode-theme#107]
![image](https://user-images.githubusercontent.com/30043375/41965055-50991a16-7a04-11e8-8a17-ed5c2e4358ff.png)

It should be the same color as simple string, but instead it's green, why?

If needed I can fix it by creating a PR.

**Comment by sdras** [comment]
No, I wanted to set these apart, this is intentional. Sometimes while working I need to see that there is a distinction. Thanks though!

**Comment by bsvipas** [comment]
@sdras At first I thought it was bug and you forget to set coloring for template literals, but now I can agree it sounds like a feature because you can easily spot the difference and sometimes it really matters. You're smart @sdras :)
