### ISSUE TITLE
Go italics & coloring

### ISSUE THREAD

**Issue by bsvipas** [sdras/night-owl-vscode-theme#108]
I saw Go colors are not consistent with JS/TS colors, so to keep it the same between switching the langs I think it makes sense to improve Go coloring and add some italics.

Here it's what I did to fix all the Go problems. I used this file to test colorings: https://golang.org/src/net/http/request.go

```
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": [
          "source.go keyword.package.go",
          "source.go keyword.import.go",
          "source.go keyword.function.go",
          "source.go keyword.type.go",
          "source.go keyword.struct.go",
          "source.go keyword.interface.go",
          "source.go keyword.const.go",
          "source.go keyword.var.go",
          "source.go keyword.map.go",
          "source.go keyword.channel.go",
        ],
        "settings": {
          "fontStyle": "italic"
        }
      },
      {
        "scope": [
          "source.go constant.language.go",
          "source.go constant.other.placeholder.go"
        ],
        "settings": {
          "foreground": "#ff5874",
        }
      },
      {
        "scope": "source.go keyword.control.go",
        "settings": {
          "foreground": "#c792ea",
          "fontStyle": "italic"
        }
      }
    ]
  },
```

![go](https://user-images.githubusercontent.com/30043375/41965736-f377c394-7a05-11e8-8531-e4b29683ed5f.png)

If needed I can create a PR.

**Comment by sdras** [comment]
Ah great, yes that is better. I would love a PR for this.

**Comment by bsvipas** [comment]
I'm happy you liked it!

1. What do you think about `func` coloring and italic, should it be the blue as it's and non-italic like in JS/TS?
2. Also, what is your opinion about so much italic things since `if`, etc. are non-italic in JS/TS.
3. Also, what about `var`, `const`, they are italic too, not like in JS/TS.

/cc @sdras

**Comment by bsvipas** [comment]
Opened a PR: #112

**Comment by sdras** [comment]
Done!
