### ISSUE TITLE
class, extends, interface, enum, type - JS/TS

### ISSUE THREAD

**Issue by bsvipas** [sdras/night-owl-vscode-theme#109]
1. In my opinion `class`, `interface`, `enum`, `type` should be the same color.
2. `extends/implements` isn't consistent with `class` keyword.
3. `extends React.Component` isn't consistent too because `React` is white while `Component` is green, they should be the same color.

![js ts](https://user-images.githubusercontent.com/30043375/41966863-e73f9130-7a08-11e8-9d36-5671486d588e.png)

**This image is from TS, but `1.` problem is in JS too.**

**Comment by bsvipas** [comment]
If needed I can create a PR.

**Comment by sdras** [comment]
This is actually intentional- with all of the other intentional things in this theme that you're not into, maybe it would be good to pursue another theme? There were a lot of choices made to set things apart for contrast that other themes don't draw a hard line on and have more consistency :) you might like them better.

**Comment by bsvipas** [comment]
@sdras I love this theme. I just want to improve it, that's why I spent my time to report all these issues (it looked like issues for me), but now some of them seems like a good features after you explained them to me. It just looks a little bit weird to see some different things like italic for `vars` instead of non-italic, `React` white instead of orange and maybe `interface` needs to be the same as `class`, but `type`, `enum` can be as it's (I guess). TS almost = JS so I don't understand why it needs to be different. I'm changing across different languages and I want it to be consistent, I can easily spot the difference by looking at file extension, file icon or type system, etc. if you mean this.

So if I ever create new issue, remember I want to help you and I love this theme. I like it, I really appreciate your work and I know how hard it's to create and to maintain a theme when everybody have their own opinion about colors.
