### ISSUE TITLE
ignored files too pronounced

### ISSUE THREAD

**Issue by placenamehere** [sdras/night-owl-vscode-theme#11]
👋🏻

Files in the file explorer that have been .gitignored tend to be colored in a muted way, with less contrast against the background, in most themes. With Night Owl, they feel almost more pronounced in color and I find it a bit distracting to me. Maybe there's a darker blue that still gives enough contrast to be readable?

Screenshots of this theme & Dark "(Visual Studio)":

<img width="308" alt="File Explorer with Night Owl" src="https://user-images.githubusercontent.com/129759/40240671-16eb35b6-5a87-11e8-84e1-841e92faa6bc.png">
<img width="355" alt="File Explorer with Dark (Visual Studio)" src="https://user-images.githubusercontent.com/129759/40240672-16fb3f38-5a87-11e8-9958-8034e0f35236.png">

**Comment by sdras** [comment]
ah yeah, thanks! I had originally muted them so much they were not accessible, then I think I went too far in the other direction. I think the solution is to bring the regular files up just a bit and then drop the gitignored files down. I'll get to this soon! Thanks for reporting.

**Comment by sdras** [comment]
This is now fixed! I also fixed the modified file color as well, which used to be too strong. Thanks!
