### ISSUE TITLE
Highlight Terminal Tabs when Selected

### ISSUE THREAD

**Issue by deadcoder0904** [sdras/night-owl-vscode-theme#115]
**Screenshots**
<img width="1216" alt="nightowl" src="https://user-images.githubusercontent.com/16436270/42349017-f044ae02-80c8-11e8-87f4-9e47acccd443.png">

As you can see in the Terminal above, I have selected Terminal tab but can't be sure its selected since its not highlighted properly. Same goes with other tabs.

PS - I love this theme. I earlier tried this & didn't like it as it was too much dark for my eyes but now its night & I again tried it & it looks beautiful. I earlier used the beautiful [Material Palenight Theme](https://marketplace.visualstudio.com/items?itemName=whizkydee.material-palenight-theme) but can't use a theme for more than a year LOL 😂 so this is nice. Thank you, Sarah 🙇‍♂️

And as for Material Palenight Theme screenshot regarding the selected tab, this is how it looks like - 

<img width="1222" alt="palenight-italic" src="https://user-images.githubusercontent.com/16436270/42349320-03efca3a-80ca-11e8-8b9f-8ceff785654e.png">

As you can see the selected tab should be highlighted 👆

**Comment by sdras** [comment]
Yep that's a bug for sure! Thanks for pointing it out, I'll take a look soon.
