### ISSUE TITLE
Syntax color highlighting in React tags and text are the same color

### ISSUE THREAD

**Issue by sunnyday90210** [sdras/night-owl-vscode-theme#117]
Possible issue with Syntax color highlighting in React. Tags and text are showing the same color. Also, the import statement does not match the color them in the demo. Mine is showing green and it should be purple.

![screenshot_1](https://user-images.githubusercontent.com/26734422/42424810-8c183ccc-82c7-11e8-8be4-7d092ceee0ca.png)

**Comment by palashmon** [comment]
Hi, thanks for reporting this.

I have a few queries:
1. What is the file type for this code? `.js`, `.jsx` or `.ts`?
2. Are you using any syntax highlighting extensions like [`Sublime Babel`](https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode) or something else?

Regards!

**Comment by sunnyday90210** [comment]
You are totally right I must have installed babel syntax highlighter a long time ago when some of my themes did not support it. I just disabled it now everything is fine, this was my fault the issue can be closed. Thanks again for such a beautiful theme.

**Comment by fpigeonjr** [comment]
same issue but then uninstalled the `Babel Javascript` extension and now its fine.
