### ISSUE TITLE
CSS syntax highlighting

### ISSUE THREAD

**Issue by morajabi** [sdras/night-owl-vscode-theme#119]
**Describe the solution you'd like**
I think having CSS highlighting is so cool! Or we already have it and I'm missing it? :)
<img width="694" alt="screen shot 2018-07-12 at 4 07 27 pm" src="https://user-images.githubusercontent.com/12202757/42630884-b0689c6a-85ed-11e8-9945-506f25c0e066.png">

**Comment by sdras** [comment]
I'm sorry, I'm not sure what you're referring to here, the screenshot you posted has syntax highlighting? can you please be more specific?

**Comment by sdras** [comment]
Closing this out due to inactivity. Please feel free to reopen if you have more info. Thanks.
