### ISSUE TITLE
Toggling the Side Bar causes: "Cannot read property 'setVisible' of undefined"

### ISSUE THREAD

**Issue by rbelliard-vivial** [sdras/night-owl-vscode-theme#12]
# Issue
When I'm on the Source Control side bar, pressing `ctrl+B` to toggle it causes the following error:

	Cannot read property 'setVisible' of undefined

* See demo [here](https://drive.google.com/file/d/1Ttjqz66ML4lRmq_TYdgskZDuXjbiEfNT/view).

# System info
VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 4.15.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.39GB (1.09GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-toggle-quotes|Bri|0.3.1
bracket-pair-colorizer|Coe|1.0.50
vscode-markdownlint|Dav|0.16.0
EditorConfig|Edi|0.12.2
code-settings-sync|Sha|2.9.2
project-manager|ale|0.25.2
vscode-custom-css|be5|2.7.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
mustache|daw|1.1.1
jshint|dba|0.10.18
vscode-eslint|dba|1.4.9
githistory|don|0.4.1
eslint-disable-snippets|drK|1.1.4
gitlens|eam|8.3.0
tslint|eg2|1.0.29
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.3.1
auto-close-tag|for|0.5.6
vsliveshare|ms-|0.3.125
debugger-for-chrome|msj|4.4.3
vscode-code-outline|pat|0.2.1
vscode-icons|rob|7.23.0
vscode-fileutils|sle|2.8.1
es6-mocha-snippets|spo|0.1.3
addDocComments|ste|0.0.8
vscode-import-cost|wix|2.6.2
ReactSnippets|xab|2.1.0

(3 theme extensions excluded)

</details>

**Comment by sdras** [comment]
Dang, sorry about that. I appreciate the screencast here, I'll try to track it down. Thanks!

**Comment by sdras** [comment]
I can't recreate this on any machine, can you please upgrade to the latest version and try again? And also try a few different themes and let me know if you're having this issue on all of them or just mine? Thanks!

**Comment by sdras** [comment]
I've tested this a bunch and it seems like it's not a problem with the theme, but something might be b0rked with your code install. Feel free to reopen if you disagree and we can talk it through.
