### ISSUE TITLE
SEText-style Markdown Heading Colors

### ISSUE THREAD

**Issue by cheilman** [sdras/night-owl-vscode-theme#122]
**Describe the solution you'd like**

If you mix markdown heading styles, then only the atx styles (###) are colored.  The Setext-style (underlines) are not.

```
Heading 1
========

Heading 2
--------------

### Heading 3
```

I'm not sure how to contribute w/ theme development, but I got this to work with the following customization settings.  It just reuses the same color as the other headings, which is fine for me.  I don't know if other people like having a different color for headings.

```json
    "editor.tokenColorCustomizations": {
        "[Night Owl No Italics]": {
            "textMateRules": [
                {
                  "name": "Markdown Heading Underline (H1)",
                  "scope": "markup.heading.setext.1.markdown",
                  "settings": {
                    "foreground": "#82b1ff"
                  }
                },
                {
                  "name": "Markdown Heading Underline (H2)",
                  "scope": "markup.heading.setext.2.markdown",
                  "settings": {
                    "foreground": "#82b1ff"
                  }
                },
            ]
        }
    },
```

**Comment by sdras** [comment]
oh great, thank you for reporting this! I'll get to it soon. Definitely a bug on my part.

**Comment by cheilman** [comment]
Thanks so much! Love the theme :-)

**Comment by sdras** [comment]
This should be fixed now! One thing- I can't alter the words, only the underline, so that's what's fixed. Thanks :)
