### ISSUE TITLE
Object inside class

### ISSUE THREAD

**Issue by duranivan** [sdras/night-owl-vscode-theme#124]
**Describe the solution you'd like**
First of all, thanks for an awesome theme @sdras , this is my default theme right now. One thing I noticed is that when an object is inside a class (in Javascript), it looks different than when outside the class.

This is how it looks right now:
 
![code2](https://user-images.githubusercontent.com/20104703/43364886-e84d22a2-933c-11e8-9d2c-a50969712701.png)

This is what I would expect:

![code1](https://user-images.githubusercontent.com/20104703/43364889-f70f7a92-933c-11e8-88e6-3b4e3eb7fe5f.png)

Also, could `const, let, var, this` and function arguments be italicized as well 😝 ?

**Comment by sdras** [comment]
Hi, I used to have more italics but after a ton of feedback, reduced the incidence of it. I'm not using purple in this way but I might think about making the keys another color. Thanks.

**Comment by sdras** [comment]
Fixed! I had to do it a different way due to the other things that were affected, but there's better contrast now :)

**Comment by duranivan** [comment]
That sounds great, thanks :)
