### ISSUE TITLE
Add official support for Clojure(Script) syntax highlighting

### ISSUE THREAD

**Issue by Jarzka** [sdras/night-owl-vscode-theme#126]
Related to my PR: https://github.com/sdras/night-owl-vscode-theme/pull/125

Here is a screenshot of the current syntax highlighting when using Clojure / ClojureScript language with Night Owl theme:

https://imgur.com/a/ATrvYWG

I can see three problems here:

- Keywords are not highlighted. For those who don't know Clojure, keyword is a special kind of type in Clojure. It is mostly used in maps as a key, but it can also be used as a function. It's NOT the same thing as keyword in other languages (those are primary language-level commands, like if, for, while etc.). I have no strong opinion about the color that should be used, as long as it's different that what is already used for other things.
- Some function/macro calls are colored differently (ns, defn VS if, let VS assoc, str). I think all function / macro calls should use the same color.
- set-age is not dimmed, even if it's now used.

However, when using VS Code with the default theme, the exact same problems are also there, but of course with different colors. I wonder if the root cause for these is that VS Code (or the Clojure plugin) is not properly optimised for Clojure? Or, at least not how I'd like things to work. :)

Here is a screenshot of my tuned version of the Night Owl theme for IntelliJ IDEA. I think the theme for VS Code should look more like this:

https://imgur.com/a/wfns5YW

**Comment by sdras** [comment]
Awesome, thanks! I should be able to get to it in the next couple weeks.

**Comment by sdras** [comment]
<img width="731" alt="Screen Shot 2019-04-05 at 8 56 22 PM" src="https://user-images.githubusercontent.com/2281088/55664077-e7d2f400-57e5-11e9-8cc7-ef4fa9db6e88.png">

Fixed! Please upgrade and restart
