### ISSUE TITLE
Add TextMate, Ace, and RStudio themes to community ports ☺️

### ISSUE THREAD

**Issue by batpigandme** [sdras/night-owl-vscode-theme#128]
Hey Sarah,

Decidedly obsessed with this theme, so I ported it (to the best of my limited abilities) for TextMate, Ace, and RStudio [here](https://github.com/batpigandme/night-owlish).

If it meets your standards of excellence (no sarcasm…you've done a great job, and are totally entitled to quality control), I'm happy to submit a PR adding it to the README, or you can add it yourself (totally up to you) — I just always try to file an issue before moving to PR!

💖,
Mara (and the Batpig, and Teddy, obviously)

**Comment by palashmon** [comment]
Hi, thanks for your contribution. Please create a PR for this and I will let @sdras know about it so that she can review & merge it whenever she is free. Also, please follow the format as it is done in PR #132

Regards!
