### ISSUE TITLE
Reliance on git

### ISSUE THREAD

**Issue by sdras** [sdras/night-owl-vscode-theme#13]
A windows user reported needing git to install, that should not be the case.

**Comment by mikekidder** [comment]
Sarah, dont think that has anything to do with your theme extension.   

If VS Code (upon launch) cannot find Git, a terminal window will open asking to download or configure the path.

![image](https://user-images.githubusercontent.com/41694/40245189-1de69a72-5a82-11e8-8c91-e80f34080eac.png)

Just downloaded VS Code onto a VM I had, with no Git installed

**Comment by sdras** [comment]
Ah, interesting, I thought it was because of the repo type. Thanks for checking this out!
