### ISSUE TITLE
Style Breadcrumb Bar

### ISSUE THREAD

**Issue by mikeerickson** [sdras/night-owl-vscode-theme#131]
With the release of Breadcrumbs in latest VSCode release (1.27 release and above) could you please consider styling these new elements.  As I am sure you are aware, the current breadcrumb style is using the default VSCode colors, would like to see it look as purdy as rest of the UI

![image](https://user-images.githubusercontent.com/183153/44223363-4571dd80-a13c-11e8-8732-cca63daf3128.png)

**Comment by palashmon** [comment]
Hi, thanks for reporting this. This should be fixed with PR #130. Please wait for the next release.

Regards!

**Comment by svipben** [comment]
@sdras This can be closed since it was fixed in #130.

**Comment by sdras** [comment]
Thanks!
