### ISSUE TITLE
Font ligatures (italic) is not working

### ISSUE THREAD

**Issue by betrocker** [sdras/night-owl-vscode-theme#133]
I just installed this theme in VSCode 1.27.1 and I installed Dank Mono font on my mac but I don't get font italic ligatures (for ex. for import, extends, from in React file).

What could be a problem?

I enabled ligatures in VSC settings and set font to "Dank Mono".

**Comment by palashmon** [comment]
Hi, thanks for reporting this. Could you please share some screenshots of what exactly the issue is and what is the expected behaviour, if possible?

Regards!

**Comment by sdras** [comment]
Hi @betrocker- 
Do your preferences look like this?
```
  "editor.fontFamily": "Dank Mono",
  "editor.fontLigatures": true,
```
Also there is an italics and no-italics version, can you please make sure you activated the right one? Thanks!

**Comment by betrocker** [comment]
Here's my settings

![screen shot 2018-09-18 at 22 34 13](https://user-images.githubusercontent.com/16548557/45714901-3646db00-bb93-11e8-8db5-c588ba99e101.png)

**Comment by sdras** [comment]
That's strange- everything looks correct to me. Can you please try reloading VS Code and the theme?

**Comment by ritabradley** [comment]
I'm also experiencing this issue, but I'd like to note it's not limited to your theme for me. However, when I change my font back to Fira Code to see if I can reproduce the issue, my ligatures work for that font. I've reloaded VSCode and the theme and the issue persists.

![screen shot 2018-11-17 at 12 52 13 am](https://user-images.githubusercontent.com/41173740/48659313-e2763800-ea03-11e8-9b91-31c668946a37.png)
![screen shot 2018-11-17 at 12 54 15 am 2](https://user-images.githubusercontent.com/41173740/48659315-e73aec00-ea03-11e8-8fc9-c687768e4949.png)

**Comment by ritabradley** [comment]
I was having the same problem, but I reinstalled the font, and the ligatures worked.

**Comment by betrocker** [comment]
It's still the same.

![screen shot 2018-11-21 at 09 39 27](https://user-images.githubusercontent.com/16548557/48829002-7718c700-ed71-11e8-9b36-ca83d8ba399b.png)

**Comment by sdras** [comment]
I'm seeing the ligature in the arrow, sorry, what behavior are you expecting?

**Comment by betrocker** [comment]
Like I said in my initial post - some of the ligatures are not working (like IMPORT, FROM, EXTENDS)

**Comment by sdras** [comment]
Those aren't ligatures, those are italics :) - I got negative feedback on the amount of italics so was convinced to use them more sparingly. Your screenshot is the expected behavior.

**Comment by franncode** [comment]
For future users who are looking for a solution to this problem, they need to add the following to their settings.json in Visual Studio Code:

	"editor.tokenColorCustomizations": {
		"textMateRules": [
			{
				"scope": [
					//following will be in italic (=FlottFlott)
					"comment",
					"entity.name.type.class", //class names
					"keyword", //import, export, return…
					"constant", //String, Number, Boolean…, this, super
					"storage.modifier", //static keyword
					"storage.type.class.js", //class keyword
				],
				"settings": {
					"fontStyle": "italic"
				}
			},
			{
				"scope": [
					//following will be excluded from italics (VSCode has some defaults for italics)
					"invalid",
					"keyword.operator",
					"constant.numeric.css",
					"keyword.other.unit.px.css",
					"constant.numeric.decimal.js",
					"constant.numeric.json"
				],
				"settings": {
					"fontStyle": ""
				}
			}
		]
	}

**Comment by kasper369-proxy** [comment]
how do you address functions and var and props

**Comment by TheFunkyMonk** [comment]
> how do you address functions and var and props

You can add `"storage.type.js"` to the first `"scope"` array for this.

And for anyone who ended up here trying to solve this problem, you can find any selector scopes by pressing `ctrl/cmd + shift + p`, and looking for `Developer: Inspect Editor Tokens and Scopes`.
