### ISSUE TITLE
selected language in snippet panel is hard to see

### ISSUE THREAD

**Issue by xiaoyu-tamu** [sdras/night-owl-vscode-theme#134]
Open user snippet config, and use array key to navigate. You can see that the default theme is easy to identify current selected item.

![screen shot 2018-09-11 at 10 32 13 am](https://user-images.githubusercontent.com/33362998/45370566-24bb6d00-b5ae-11e8-820a-696762b14327.png)

![screen shot 2018-09-11 at 10 33 20 am](https://user-images.githubusercontent.com/33362998/45370593-2b49e480-b5ae-11e8-87c3-9ea1744280fc.png)

**Comment by sdras** [comment]
Oh good call! Thanks for reporting this, I'll try to fix soon.

**Comment by svipben** [comment]
@xiaoyu-tamu seems like duplicate of https://github.com/sdras/night-owl-vscode-theme/issues/139?

**Comment by xiaoyu-tamu** [comment]
@svipben yeah. closing it.
