### ISSUE TITLE
Status Bar Foreground Color with Vim

### ISSUE THREAD

**Issue by joshmedeski** [sdras/night-owl-vscode-theme#135]
While using the [vim plugin](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) the status bar colors don't work very well with the night owl default text color (it's like a blueish gray).

I have control of the background colors(s) depending on the mode but most of the colors I chose don't look good with the current foreground color.

Is it possible to change the foreground color if the vim plugin is enabled to something more neutral like plain white? Or some way to just overwrite it in my settings?

**Screenshot**
<img width="1333" alt="screen shot 2018-09-12 at 9 14 37 am" src="https://user-images.githubusercontent.com/2036594/45431009-51ce5500-b66c-11e8-9c17-f0b52016ffb4.png">

**Comment by ryzokuken** [comment]
@joshmedeski VSCodeVim allows you to set the foreground color of the status bar for each mode.

**Comment by joshmedeski** [comment]
Thanks @ryzokuken, I had to use the array syntax on the [vim-airline settings](https://github.com/VSCodeVim/Vim#vim-airline)
