### ISSUE TITLE
Color mismatch

### ISSUE THREAD

**Issue by jcoleman-techempower** [sdras/night-owl-vscode-theme#136]
### Night Owl 0.4.1

In previous versions for JS, the `const` keyword and the variable name used to be two separate colors. They are currently the same color.

Also, an object literal's keys may be colored purple, however an object as an argument's keys are only white.

Here is a picture with a pretty good example of both.

![screenshot from 2018-09-13 10-02-12](https://user-images.githubusercontent.com/43076128/45503581-25820980-b73c-11e8-9087-8042c74e4202.png)

**Comment by sdras** [comment]
Thanks! Yeah I think this problem started in a recent release, I'll try to track it down and get back to you.

**Comment by jacksonStone** [comment]
Was able to add this to vscode user config to seemingly fix the issue:

```
"editor.tokenColorCustomizations": {
        "textMateRules": [
          {

            "name": "Built-in constant",
            "scope": [
                "constant.language",
                "punctuation.definition.constant",
                "variable.other.constant"
            ],
            "settings": {
                "foreground": "#FFFFFF"
            }
          }
        ]
      }
```

**Comment by EddyVinck** [comment]
> Was able to add this to vscode user config to seemingly fix the issue:
> 
> ```
> "editor.tokenColorCustomizations": {
>         "textMateRules": [
>           {
> 
>             "name": "Built-in constant",
>             "scope": [
>                 "constant.language",
>                 "punctuation.definition.constant",
>                 "variable.other.constant"
>             ],
>             "settings": {
>                 "foreground": "#FFFFFF"
>             }
>           }
>         ]
>       }
> ```

adding `"fontStyle": ""` to the `settings` object removed the italic font too!

![image](https://user-images.githubusercontent.com/23434753/47314235-6590b200-d641-11e8-94fb-4b49658b06e4.png)

**Comment by jcoleman-techempower** [comment]
@jacksonStone @EddyVinck I would prefer not to modify my settings and wait for the author to fix this issue. But I'm glad y'all got it working for yourselves

**Comment by sdras** [comment]
this is fixed!
