### ISSUE TITLE
Improve C++ highlighting

### ISSUE THREAD

**Issue by ryzokuken** [sdras/night-owl-vscode-theme#138]
Thanks for this awesome theme, @sdras! I absolutely love it while writing JavaScript. That said, while writing C++, the theme makes everything... blue (no puns intended).

Screenshot:

<img width="1440" alt="screen shot 2018-09-18 at 2 17 07 am" src="https://user-images.githubusercontent.com/13121330/45649579-5a4de200-bae9-11e8-913d-43ab686ec79c.png">

It'd be absolutely delightful if you could take the time to make it work just as well on C++.

**Comment by palashmon** [comment]
Hi, thanks for reporting this. Could you please create a PR and add a sample C++ file inside the `demo` folder which might be used by other c++ devs as a starting point to fix this issue.

Regards!

**Comment by ryzokuken** [comment]
@palashmon sure! Should I just use an actual, working C++ file or do I just hack up a quick sample that uses as many language features in the smallest number of lines?

**Comment by palashmon** [comment]
A quick sample that uses as many language features would be great.

**Comment by sdras** [comment]
Hi @ryzokuken! Thanks for pointing this out. I agree that's too much blue. I would be happy with a PR for C++ file so that I can work on it.

**Comment by ryzokuken** [comment]
Hi @sdras! Sorry I couldn't find the time to push a sample C++ file, would try to do that by today. Thanks for agreeing to work on this.

**Comment by sdras** [comment]
This should be fixed now! Sorry for the delay. Let me know what you think.
