### ISSUE TITLE
Markdown coloring

### ISSUE THREAD

**Issue by svipben** [sdras/night-owl-vscode-theme#141]
There's no coloring for `this string`.

![image](https://user-images.githubusercontent.com/10441177/45929771-f307b600-bf5e-11e8-8b99-89d0c36119c2.png)

**Comment by palashmon** [comment]
You mean in the *.md file type the string inside `` should have some colouring like:

![code2](https://user-images.githubusercontent.com/14850464/45965329-ced2d480-c045-11e8-95bb-9c7b87d444a9.png)

**Comment by svipben** [comment]
@palashmon Yes!
