### ISSUE TITLE
Python function definition italic and color

### ISSUE THREAD

**Issue by yelfathi** [sdras/night-owl-vscode-theme#143]
The def keyword should be in italic and with a different color (like the other keywords for/if) than the function name.
Please see below between Night Owl and default Dark+ theme.
![capture](https://user-images.githubusercontent.com/9952320/46105695-fdcc8000-c1d6-11e8-9d2a-6f3fe0a541d9.PNG)

![capture 2](https://user-images.githubusercontent.com/9952320/46105700-002eda00-c1d7-11e8-9bd8-0bacbbe4f84f.PNG)

Thanks!

**Comment by svipben** [comment]
This behavior is also in JS/TS. We need to use different coloring for `function` keyword. Also, the different keyword for Python `def` as well.

Also, as I can see Python have bad coloring for `from`, `import`, `if`, `for`, `return` keywords, they should be `#c792ea` instead of `#7fdbca`

**Comment by sdras** [comment]
Good point, I'll work on this next. thanks!
