### ISSUE TITLE
Html attributes in pug

### ISSUE THREAD

**Issue by mickaelchanrion** [sdras/night-owl-vscode-theme#150]
Thanks for this theme, it looks good! 

But I found a bug:

In a `.vue` file using pug, only the first attribute (with a `:`) is on italic style

<img width="487" alt="screen shot 2018-10-11 at 09 24 05" src="https://user-images.githubusercontent.com/8982274/46791038-29537c80-cd38-11e8-96e9-cb82e1fe3b20.png">

If I add 2 spaces between attributes, it's ok:
<img width="703" alt="screen shot 2018-10-11 at 09 33 33" src="https://user-images.githubusercontent.com/8982274/46791378-ea71f680-cd38-11e8-923a-d144ada52d4c.png">

Also, if I use a new line for each it's ok:
<img width="494" alt="screen shot 2018-10-11 at 09 33 59" src="https://user-images.githubusercontent.com/8982274/46791423-070e2e80-cd39-11e8-8d74-55f7e35904bf.png">

**Comment by sdras** [comment]
oh strange! would you mind terribly committing the file to the demo folder? makes it easier for me to debug. if you're too busy, no worries- it will just take me a bit longer to get to it.

Thanks!

**Comment by mickaelchanrion** [comment]
NP, I'll do it ;)

**Comment by sdras** [comment]
closing this out because I can't duplicate and don't have the demo file, but if you feel like PRing the demo file, we can reopen :)
