### ISSUE TITLE
Highlighting code block in markdown

### ISSUE THREAD

**Issue by mittalyashu** [sdras/night-owl-vscode-theme#151]
**Screenshots**

![image](https://user-images.githubusercontent.com/29014463/46946824-9cd9ee80-d096-11e8-8fb6-324f1227d1f2.png)

There should be separate color for highlighting the code block.

**Comment by svipben** [comment]
It was already merged (fixed), but not yet released. https://github.com/sdras/night-owl-vscode-theme/pull/142

@sdras Maybe you want to release new Night Owl updates which contain several important fixes?

**Comment by mittalyashu** [comment]
Okay

**Comment by sdras** [comment]
This should be fixed now, please feel free to reopen if I'm mistaken.
