### ISSUE TITLE
Border/Color on notification

### ISSUE THREAD

**Issue by mittalyashu** [sdras/night-owl-vscode-theme#152]
**Screenshots**

![code - insiders_2018-10-20_19-56-33](https://user-images.githubusercontent.com/29014463/47267232-c2676c00-d55e-11e8-9316-9a5a612b34b9.png)

There is no borders on each notifications which makes it hard understand the notification area _(size)_, until we hover on each of them.

**Solutions**

* Use different background color on each of them.

**Comment by lightify97** [comment]
Well using different background on each notification seems an overkill. However a different background and a border would suffice.

**Comment by sdras** [comment]
Yeah, I agree with @lightify97 about having a border here. Possibly background but I try to keep from having too much going on unnecessarily. Thanks, I'll look into this!

**Comment by sdras** [comment]
Added a background and a border. Thanks! Please upgrade and restart!
