### ISSUE TITLE
No Italics Theme: Italics showing up in diffs

### ISSUE THREAD

**Issue by kentor** [sdras/night-owl-vscode-theme#153]
**Please make sure you're using the latest version of the plugin before submitting an issue**

**Screenshots**
There are still italics in the no italics theme, see: https://github.com/sdras/night-owl-vscode-theme/blob/master/themes/Night%20Owl-color-theme-noitalic.json#L220

They should be removed?

![image](https://user-images.githubusercontent.com/240493/47320715-17f75380-d607-11e8-8c39-8ec58c815801.png)

**Comment by sdras** [comment]
Fixed with your PR, closing.
