### ISSUE TITLE
Markdown punctuation color

### ISSUE THREAD

**Issue by svipas** [sdras/night-owl-vscode-theme#159]
<img width="666" alt="screenshot at oct 31 12-34-15" src="https://user-images.githubusercontent.com/10441177/47785840-95f7e080-dd12-11e8-9979-ae1607f80d5d.png">

As you can see markdown punctuation near `x` char is blue `#82b1ff` which is wrong cuz' it should be white `#d6deeb`

**Comment by sdras** [comment]
Fixed in 0.5.0! May need a restart to see the changes. Thanks!
