### ISSUE TITLE
suggestion for colors

### ISSUE THREAD

**Issue by mobayen** [sdras/night-owl-vscode-theme#16]
it's not an issue. I've made these changes of colors to make it fit my  needs
thought it might be helpful 

`
"diffEditor.insertedTextBackground": "#99b76d20",
"diffEditor.removedTextBackground": "#ef535020",
"diffEditor.insertedTextBorder": "#00000000",
"diffEditor.removedTextBorder": "#00000000",
"tab.activeForeground": "#00ccff",
"tab.inactiveForeground": "#5f7e9799",
"editor.selectionHighlightBackground": "#ffffff22",
"editorIndentGuide.background": "#05508d22",
"editorGutter.background": "#00000011",
"sideBar.background": "#011423",
"editorHoverWidget.background": "#01111e",
"panel.border": "#5f7e9728",`

**Comment by sdras** [comment]
Thanks, but I'm gonna stick with my own color scheme here, I'm intentionally not using solid black.

**Comment by mobayen** [comment]
there is no solid black.
all are transparent
