### ISSUE TITLE
Italics are not working and colors are different

### ISSUE THREAD

**Issue by escalonc** [sdras/night-owl-vscode-theme#162]
I really like this theme is awesome.

But recently I installed on Linux Mint 19, the latest version of vscode(1.30.1) and night owl(0.4.2),
then I compare my setup with a screenshot in the readme and I realized that they are not the same.

![image](https://user-images.githubusercontent.com/5721978/50231971-95281600-0375-11e9-9a38-39cdaea559fd.png)

My vscode config is:
```
{

  "editor.fontFamily": "Dank Mono, Fira Code",
  "sync.autoDownload": true,
  "sync.autoUpload": true,
  "sync.forceDownload": false,
  "sync.quietSync": true,
  "sync.askGistName": false,
  "sync.removeExtensions": true,
  "sync.syncExtensions": true,
  "workbench.startupEditor": "newUntitledFile",
  "git.enableSmartCommit": true,
  "workbench.iconTheme": "file-icons",
  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
  "files.exclude": {
    "**/node_modules/": true,
    "**/venv": true
  },
  "workbench.colorTheme": "Night Owl",
  "editor.minimap.enabled": false,

  "git.autofetch": true,
  "window.zoomLevel": 2,
  "editor.cursorBlinking": "expand",
  "terminal.integrated.rendererType": "dom",
  "editor.renderLineHighlight": "all",
  "terminal.integrated.cursorBlinking": true,

  "bracket-pair-colorizer-2.forceIterationColorCycle": true,

  "terminal.integrated.cursorStyle": "line",
  "javascript.updateImportsOnFileMove.enabled": "always",

  "projectManager.git.baseFolders": [
    "/home/chris/Source",
    "/home/chris/Source/Personal",
    "/home/chris/Source/HeroUnit"
  ],
  "projectManager.git.ignoredFolders": [
    "node_modules",
    "out",
    "typings",
    "test",
    "tests",
    "venv"
  ],
  "projectManager.git.maxDepthRecursion": 4,

  "cSpell.userWords": ["Birthdate", "Formik", "Typegoose", "typeorm"],
  "zenMode.centerLayout": false,
  "terminal.integrated.fontFamily": "Dank Mono, Fira Code",
  "editor.fontLigatures": true,

  "typescript.updateImportsOnFileMove.enabled": "always",
  "editor.formatOnSave": true
}
```

**Comment by SigmundurMorkore** [comment]
I have the same issue:
![code](https://user-images.githubusercontent.com/39065262/50743215-03415980-120d-11e9-8a74-a5568f1e9136.png)

**Comment by escalonc** [comment]
@SigmundurMorkore after research in my current setup, I found that an extension was creating a conflict the theme, I couldn't remember which extension was, try to disable all your extension and just leave the theme.

**Comment by SigmundurMorkore** [comment]
Ooh, that actually worked!
Now to manually enable extensions and check which one if breaking it :P

**Comment by SigmundurMorkore** [comment]
There is however one inconsistency that I can see, between my JavaScript class color and the ones in the images. Mine is blue like the functions, but that should be easy to fix with a custom styling.

It also seems like the offending extensions were Babel JavaScript by Michael McDermott and Babel ES6/ES7 by dzannotti

**Comment by ShawonAshraf** [comment]
I found these two extensions to be in conflict with the theme. (There can be more, I had these two installed and were causing trouble rendering italics.)

- [Babel JavaScript](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel)
- [Babel ES6/ES7](https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring)
