### ISSUE TITLE
Poor contrast for highlighted items in search

### ISSUE THREAD

**Issue by tconroy** [sdras/night-owl-vscode-theme#165]
Hey @sdras! Love the theme, thanks for sharing it with all of us!

I've been using it for a couple weeks and I've noticed that the selected item in search results is very difficult to read. This is also true for selecting rows in the "problems" pane (ie TypeScript errors). See below screenshot.

Any way to increase the contrast on these selected items so they become more readable? 

**Screenshots**
![screen shot 2019-01-18 at 7 07 26 pm](https://user-images.githubusercontent.com/1609336/51418932-a327ad00-1b54-11e9-86fc-afcdeec7fdb6.png)

**Comment by sdras** [comment]
Thanks for pointing this out! This should be fixed now :) let me know if you're still having issues. May need a restart.
