### ISSUE TITLE
[help] is there way to get rid of the second scope line when using bracket pair colorizer?👀

### ISSUE THREAD

**Issue by tuucan** [sdras/night-owl-vscode-theme#170]
It's kinda too opaque to ignore. 🤔

![image](https://user-images.githubusercontent.com/7063252/52359367-d4581680-2a4a-11e9-8da8-576e0893a4ab.png)

**Comment by travisboss** [comment]
If I understand you correctly in the render line showing a slightly lighter color you want to go away, this would be a question for the developer of bracket pair colorizer, not the theme creator of night owl.

https://github.com/CoenraadS/Bracket-Pair-Colorizer-2
He has a beta of a new colorizer coming out, recommend asking for this feature on his new build.

**Comment by tuucan** [comment]
I dont think that's the case, here's when bracket pair colorizer disabled

![image](https://user-images.githubusercontent.com/7063252/52425445-13e73700-2b0d-11e9-87f7-da0099b0269c.png)

**Comment by wsslstckfsch** [comment]
Have you tried "editor.highlightActiveIndentGuide": false ?

**Comment by sdras** [comment]
This above suggestion should work ^ 
It's not something I can change in the theme (or if possible, can't find it- feel free to reopen if I'm mistaken)

**Comment by zhengger** [comment]
> This above suggestion should work ^
> It's not something I can change in the theme (or if possible, can't find it- feel free to reopen if I'm mistaken)

It doesn't work.

**Comment by stockholmicrosoldering** [comment]
hi everyone. 
would you plaese tell me how to include the lines in my bracket text editor. i get confused when the code is long. they help connect the commands together. is it an extention or how can i get the lines?
