### ISSUE TITLE
The function JavaScript keyword has the same color as the function name.

### ISSUE THREAD

**Issue by MatrixV01** [sdras/night-owl-vscode-theme#174]
Hi @sdras! Thank you for my new favorite theme. Along the lines of the const issue https://github.com/sdras/night-owl-vscode-theme/issues/166 could we have a contrasting color to differentiate between the function keyword and the function name? I've added screenshots and the TM scopes from your demo js file. If you'd like me to raise a pull request I can do that. Thanks!

**Comment by MatrixV01** [comment]
![Screen Shot 2019-03-13 at 10 23 47 AM](https://user-images.githubusercontent.com/13213194/54291976-65a33700-457b-11e9-9d64-1c55fa890c71.png)

**Comment by MatrixV01** [comment]
![Screen Shot 2019-03-13 at 10 24 09 AM](https://user-images.githubusercontent.com/13213194/54292002-72278f80-457b-11e9-9fea-6a1a5bac1f52.png)
![Screen Shot 2019-03-13 at 10 24 29 AM](https://user-images.githubusercontent.com/13213194/54292003-72278f80-457b-11e9-80ec-5c07c0f12a2a.png)

**Comment by sdras** [comment]
Yep! Good call, I'll work on that.

**Comment by sdras** [comment]
Function keyword is now different from the function name :)
