### ISSUE TITLE
The syntax color and highlighting for react file is not the same as documented

### ISSUE THREAD

**Issue by ishakimanuel** [sdras/night-owl-vscode-theme#175]

**Comment by ishakimanuel** [comment]
<img width="1408" alt="Screen Shot 2019-03-17 at 08 03 44" src="https://user-images.githubusercontent.com/24494425/54483754-8de8a980-488b-11e9-8700-08ca31a80efa.png">

**Comment by sdras** [comment]
Yeah, people wanted some changes since I released- mainly having a different color for components than html tags. I haven't updated the github screenshot yet. Will do soon.

**Comment by sdras** [comment]
Hmmm, that purple for the import should be different though. Let me take a look and get back to you.

**Comment by sdras** [comment]
This looks _very_ different from what I'm seeing. Can you please 

1. Let me know what version you're on
2. PR the demo folder with this file

I'm not able to reproduce. Thanks!

**Comment by ishakimanuel** [comment]
I’m using the latest version of vscode and the js syntax color in my react project looks same like in that screenshot

**Comment by sdras** [comment]
What version of this theme are you on? It should be 0.5.0 and you may need to restart vscode. If you're still seeing this, please PR the demo folder so I can try to duplicate :)

**Comment by ishakimanuel** [comment]
Already solved in night owl version 5.0 😅.  Thank you for helping me fix this issue @sdras.

**Comment by sdras** [comment]
My pleasure! Thanks
