### ISSUE TITLE
On clicking the "Set Color theme" shows "Cannot read property 'id' of undefined" as error

### ISSUE THREAD

**Issue by anoobbava** [sdras/night-owl-vscode-theme#176]
Hi Team,
I have tried with mac os Sierra,
when I tried with installing and click on **"Set Color theme"** shows the **"Cannot read property 'id' of undefined"**

![Screen Shot 2019-03-28 at 2 10 16 PM](https://user-images.githubusercontent.com/13102185/55142966-c9c12000-5163-11e9-9438-d015242a6c7f.png)

**Comment by sdras** [comment]
Hm, strange. Have you tried `shift + ctrl P` and then `Preferences: Color Theme`, and finding the theme in there?

**Comment by sdras** [comment]
Whatever this is, I'm pretty sure it's not the theme itself, it's VS Code. Feel free to reopen if I'm mistaken!

**Comment by garcianavalon** [comment]
This error happen to me too after updating VS Code. Closing and opening again did the trick

**Comment by j13l** [comment]
Same error here, started happening since last week. Restarted VSCode, Macbook & even my fridge, still same. :(

**Comment by ShmouG** [comment]
I'm getting the same error. And the theme got deactivated and I am unable to use it. Any luck getting it patched?

**Comment by sdras** [comment]
Hey all, I'm sorry but I really don't think this is an error with the theme but rather VS Code. Could you please file an issue in their repo?

**Comment by ShmouG** [comment]
I got it to work by uninstalling it, then re-installing the theme.

**Comment by walisom360** [comment]
install dracula theme -> file -> Preferences -> Color Theme-> you select theme  preference

**Comment by erike1** [comment]
I had the same error with Atom Dark Theme after installing the jshint extension of Dirk Baeumer.

The solution is as described above by @sdras  or disabling the jshint extension

**Comment by icharge** [comment]
![image](https://user-images.githubusercontent.com/1619007/61229968-54e61600-a753-11e9-9ee2-c00d997e032e.png)

Help!

**Comment by tigerzoren** [comment]
> 
> 
> Hm, strange. Have you tried `shift + ctrl P` and then `Preferences: Color Theme`, and finding the theme in there?

Thanks, it worked!

**Comment by hmessing** [comment]
Had a theme somehow listed in settings file that was no longer installed....

**Comment by guiguziwangxu** [comment]
> Hm, strange. Have you tried `shift + ctrl P` and then `Preferences: Color Theme`, and finding the theme in there?

thank you

**Comment by krismawan4** [comment]
thanks

**Comment by hyderumer** [comment]
> install dracula theme -> file -> Preferences -> Color Theme-> you select theme preference
thanks man
