### ISSUE TITLE
Separate the Editor from the Sidebar changes the properties for other themes also

### ISSUE THREAD

**Issue by nnnkit** [sdras/night-owl-vscode-theme#177]
It would be better if it can just update the "Night Owl" theme only.

**Screenshots**
<img width="1440" alt="Screenshot 2019-04-04 at 17 41 13" src="https://user-images.githubusercontent.com/3122626/55554621-e24fae00-5700-11e9-891d-f4b63dd70fc6.png">

** Solution **

```
  "workbench.colorCustomizations": {
    "[Night Owl]": {
      "activityBar.background": "#000C1D",
      "activityBar.border": "#102a44",
      "sideBar.background": "#001122",
      "sideBar.border": "#102a44",
      "sideBar.foreground": "#8BADC1"
    }
  },
```

Thanks!

**Comment by sdras** [comment]
Thanks for your PR!
