### ISSUE TITLE
In extension panel and search panel, the selected text seems no difference to un-selected text.

### ISSUE THREAD

**Issue by WindSoilder** [sdras/night-owl-vscode-theme#181]
It's very exciting to see the light-owl theme comes out :)  For now I love the background very much.   Thanks a lot.

But a little sadly I found issue for the selected-text in the search panel and extension panel.

**Screenshots**
![屏幕快照 2019-04-08 上午8 43 27](https://user-images.githubusercontent.com/22256154/55692498-40b7ad80-59db-11e9-8f90-c038ed400a22.png)

**Description**
I have select text "owl", but there is no difference between text which is selected and un-selected.  The same thing happened in the search panel.
It just happen in the light theme, and original dark theme works fine :)

**Comment by sdras** [comment]
Ah interesting, sorry about that! I'll try to track down what happened.

**Comment by sdras** [comment]
This is fixed! Please upgrade
