### ISSUE TITLE
Dark theme's starting window too bright in versions > 1.0.0

### ISSUE THREAD

**Issue by daern91** [sdras/night-owl-vscode-theme#182]
Hi,

In the latest update the starting background got it's color changed from dark to light. This makes my eyes cry as the contrast is just too much. It was really great before since it all merged together so nicely... 

Could we please revert this? Im using `Night Owl No Italics`. Please see the difference in screenshots below. Another solution might be to simply make the vs code logo this bright and the rest darker... Just inverting the two.

**V 0.4.2**
![0 4 2_all_dark](https://user-images.githubusercontent.com/6084427/55722189-d5cf9c00-5a05-11e9-8206-0dfa7fa5d114.png)
**V 1.0.1**
![1 0 0_light_start_point](https://user-images.githubusercontent.com/6084427/55722190-d5cf9c00-5a05-11e9-97d2-22e9b3602101.png)

**Comment by tvandort** [comment]
I created a PR to restore the original background color if that ends up being the intended direction. I can't tell because the last update to the line for that color changed a deprecated color value.

https://github.com/sdras/night-owl-vscode-theme/pull/183

**Comment by sdras** [comment]
Woah, yeah that's no good. Thanks for the catch!

**Comment by sdras** [comment]
closing this out because it's merged, might do a few more changes before releasing- but sometime in the next day or so

**Comment by SavePointSam** [comment]
Thanks for this, @daern91 and @tvandort! Looking forward to the next release. I'll have to downgrade until then as the light color is super distracting.

**Comment by daern91** [comment]
Thanks a lot, @tvandort and @sdras!

No problems, @SavePointSam, @sdras is amazingly fast so the fix seems to be released already with `v1.1.0`.

**Comment by SavePointSam** [comment]
Looks like it! Thanks for the quick turn around, @sdras!! 🚀 🎉
