### ISSUE TITLE
Inactive tab text color illegible in split editor mode

### ISSUE THREAD

**Issue by hello-jason** [sdras/night-owl-vscode-theme#188]
When split editor mode is enabled, the text color in the active tab inside the inactive pane is unreadable. See screenshot for example.

v1.0.1

![bug-nightowl-inactivepanecolor](https://user-images.githubusercontent.com/1406213/55759766-de34d080-5a1f-11e9-92d9-3061700f0400.png)

**Comment by sdras** [comment]
This... should not be green though... are you sure you don't have another extension overriding mine?

**Comment by sdras** [comment]
I think this is another extension overriding my theme. I can't duplicate. I'm going to close this out. If you think I'm mistaken, please feel free to reopen :)
