### ISSUE TITLE
Some of the coloring logic seems a little off

### ISSUE THREAD

**Issue by dlinch** [sdras/night-owl-vscode-theme#19]
Specifically in Ruby:
- Class definitions keep scope resolution coloring, I think most other color palettes give the two sides of the :: two different colors. However in invocation, the two are colored properly, _unless_ I invoke `.new`, in which case it goes back to the same color.

- calling a function with a symbol as an arg is the same color, I would have expected a different color to for better contrast.

Screenshot to illustrate:
![screen shot 2018-05-18 at 3 00 55 pm](https://user-images.githubusercontent.com/5693184/40257753-980d34da-5aac-11e8-9610-a1cc7f410dcd.png)

Otherwise I love the theme! It looks great!

**Comment by sdras** [comment]
AH! I didn't have a ruby example that I was working off of. Would you mind PR-ing in an example file into the demos directory? no worries if you don't have the time, I could also do it. thanks!

**Comment by dlinch** [comment]
There you go! Let me know if you want more ruby in there to go off of.

**Comment by sdras** [comment]
Hey! Thanks for the file!

So I actually can't find a single other theme that creates a difference between before and after the `::`. It's actually not even allowing me to target them separately in TM scopes.

Here's about as good as I could do:
<img width="507" alt="screen shot 2018-05-19 at 11 26 25 am" src="https://user-images.githubusercontent.com/2281088/40271234-b3339000-5b57-11e8-8691-e70d49e7ee96.png">

For reference, here are some other popular themes, I tested out about 10 of them:
<img width="509" alt="screen shot 2018-05-19 at 11 24 47 am" src="https://user-images.githubusercontent.com/2281088/40271242-c0d1e2e8-5b57-11e8-9b8c-ed1facbae852.png">
<img width="544" alt="screen shot 2018-05-19 at 11 24 34 am" src="https://user-images.githubusercontent.com/2281088/40271247-c817ac36-5b57-11e8-93fd-97e54e328e22.png">
<img width="487" alt="screen shot 2018-05-19 at 11 24 14 am" src="https://user-images.githubusercontent.com/2281088/40271248-cf43312e-5b57-11e8-8538-83734c0b4d5a.png">

What do you think?

**Comment by dlinch** [comment]
I think that looks great! I went back to my old theme and noticed that it is the same color within a single scoping. The two different classes on either side of the `<` were what were different colors, so I think your change above is perfect! It was just when both classes and the `<` were the same color that it was a little difficult to read. 
Sorry for leading you down the rabbit hold there for getting the scope resolution operator colored :\

**Comment by sdras** [comment]
Awesome! Thanks :)
