### ISSUE TITLE
Illegible white text on JSX on the light theme

### ISSUE THREAD

**Issue by chibicode** [sdras/night-owl-vscode-theme#191]
Hi there, I love the light theme! 👍 

On the light theme, if you have this `js` file:

```js
const Foo = () => <div>
  
</div>
```

And then if you start typing `<div` in the child:

```js
const Foo = () => <div>
  <div
</div>
```

Then the last `</div>` becomes white and completely illegible:

![image](https://user-images.githubusercontent.com/992008/55763328-4d5bf600-5a1b-11e9-9fbb-6f27ef997259.png)

**Comment by sdras** [comment]
Woah! Thanks for pointing this out, I'll take a look. Thanks!

**Comment by sdras** [comment]
@redders6600 yes please, separate issues are better

**Comment by sdras** [comment]
fixed both! please update
