### ISSUE TITLE
Highlighting in the terminal is opaque/solid

### ISSUE THREAD

**Issue by jryd** [sdras/night-owl-vscode-theme#192]
This has only been an issue the last 2 days or so, however when I am highlighting text inside the integrated terminal, the highlighting is opaque/solid so that I cannot see through it.

Before highlighting:
![image](https://user-images.githubusercontent.com/13251203/55767289-96638700-5abb-11e9-9e57-08d1bb6b58cf.png)

After highlighting:
![image](https://user-images.githubusercontent.com/13251203/55767308-a67b6680-5abb-11e9-9488-da75e1bdfc7c.png)

I assume this is not by design?

**Comment by sdras** [comment]
It's a bug alright. I'll get to it soon! Sorry about that.

**Comment by jryd** [comment]
Thanks @sdras!

**Comment by sdras** [comment]
Fixed! Please update
