### ISSUE TITLE
Insufficient contrast for highlighted search matches

### ISSUE THREAD

**Issue by philipp-spiess** [sdras/night-owl-vscode-theme#195]
Search results will highlight the matched sections with a different background color but does not change the font color making it hard to read the text. 

**Screenshots**

<img width="618" alt="Screen Shot 2019-04-10 at 12 31 17" src="https://user-images.githubusercontent.com/458591/55872303-f0804d00-5b8c-11e9-9ed3-833081aac6a7.png">

**Comment by sdras** [comment]
Dang, I changed this for one context and it broke another. Thanks for filing! I'll try to fix it soon.

**Comment by sdras** [comment]
Just worked on this! Please update! (might need to restart code to see the changes) thanks for reporting!

**Comment by philipp-spiess** [comment]
@sdras Woohoo it works now! Thank you so much for fixing this so quickly 🎉
