### ISSUE TITLE
Plugin not working at all for me

### ISSUE THREAD

**Issue by shamamaz** [sdras/night-owl-vscode-theme#196]
**Please make sure you're using the latest version of the plugin before submitting an issue**
The plugin does not work for me, I am seeing an error saying `Cannot read property 'id' of undefined` when I try to set the colour theme.

**Screenshots**
![TITLE](https://user-images.githubusercontent.com/11925430/55894575-50282980-5b88-11e9-9dff-e6e79f7cc614.gif)

**Comment by sdras** [comment]
Sorry that's happening :/ Unfortunately it's not a problem with Night Owl but Code itself. I'm going to close this out, maybe try refiling in the Code repo? Feel free to reopen if I'm mistaken. 

(Try restarting Code and see if it persists)
