### ISSUE TITLE
Override comment colour

### ISSUE THREAD

**Issue by ronny** [sdras/night-owl-vscode-theme#197]
**Describe the solution you'd like**

I'd like to be able to override comment foreground colour by doing something like this in my user settings:

```json
"editor.tokenColorCustomizations": {
  "comments": {
    "foreground": "#FFFFFF",
  }
}
```
 or 
```json
"editor.tokenColorCustomizations": {
  "[Night Owl]": {
    "comments": {
      "foreground": "#FFFFFF",
    }
  }
}
```

**Is your feature request related to a problem? Please describe.**

The above override doesn't work for Night Owl, while it works for other themes. I have tried this with double slash comments and `/* .. */` style comments, for Go specifically.

Thank you!

**Comment by sdras** [comment]
Try this and let me know if it worked:

```
"editor.tokenColorCustomizations": {
  "[Night Owl]": {
    "comments": {
      "foreground": "#FFFFFF",
    },
   "comment.line.double-slash": {
      "foreground": "#FFFFFF",
    }
  }
}
```

**Comment by ronny** [comment]
@sdras Thanks for the suggestion. I tried and it didn't work unfortunately. I also tried this which didn't work either:
```json
"editor.tokenColorCustomizations": {
    "comments": {
      "foreground": "#FFFFFF",
    },
   "comment.line.double-slash": {
      "foreground": "#FFFFFF",
    }
}
```

**Comment by sdras** [comment]
Try this:

```
"workbench.colorCustomizations": {
    "comments": {
      "foreground": "#FFFFFF",
    },
   "comment.line.double-slash": {
      "foreground": "#FFFFFF",
    }
}
```

**Comment by ronny** [comment]
Didn't work either 😞 I think it may be an issue with VSCode itself. Thanks for the suggestions (and for the themes!), @sdras.

**Comment by sdras** [comment]
Ok! I'll close it out then, sorry it's not working. Let me know if you think there's something to be done.

**Comment by ronny** [comment]
I finally got this to work:

```json
  "editor.tokenColorCustomizations": {
    "[Night Owl]": {
      "comments": {
        "foreground": "#ffffff"
      },
      "textMateRules": [
        {
          "scope": "comment.line.double-slash",
          "settings": {
            "foreground": "#ffffff"
          }
        }
      ]
    }
}
```

**Comment by erantona** [comment]
None of these work for me😥😥😥

**Comment by Seungwan-Jung** [comment]
Thanks Ronny! I was searching for the exact same issue!

**Comment by arskhan741** [comment]
> None of these work for me😥😥😥

The Last script posted by Ronny worked for me. Make sure your theme name is same. My theme name was "Night Owl (No Italics)" but the theme name in script is [Night Owl].
