### ISSUE TITLE
'instanceOf' color

### ISSUE THREAD

**Issue by hollandThomas** [sdras/night-owl-vscode-theme#199]
Hey, I just noticed that the `instanceof` operator is of the same color as its operands. For example:

![instanceof](https://user-images.githubusercontent.com/20690465/56219327-d7810b80-6066-11e9-9447-742182229090.PNG)

Wouldn't it be better if `instanceof` was treated the same as e.g. `===` and therefore making it distinguishable from its operands? Or am I missing something?

![equals](https://user-images.githubusercontent.com/20690465/56219692-760d6c80-6067-11e9-9560-1a070f094f4f.PNG)

Thanks for all the work you put into this! :)

**Version**: 1.1.3

**Comment by sdras** [comment]
Good idea, I can try to see if it will let me target it 👍

**Comment by DNonov** [comment]
I think you can mach it with "keyword.operator.expression.instanceof.js.jsx".  :)

**Comment by sdras** [comment]
Thanks for the PR @nnnkit!
