### ISSUE TITLE
Can not find theme in VS Code or Online 

### ISSUE THREAD

**Issue by tbsvttr** [sdras/night-owl-vscode-theme#2]
I can not find the theme in my local VS Code or online in the search of the marketplace (https://marketplace.visualstudio.com/search?term=night-owl-vscode-theme&target=VSCode&category=All%20categories&sortBy=Relevance).

**Comment by sdras** [comment]
I just started it a few hours ago. It's not fully released yet :) I'll probably be done tomorrow.

**Comment by vikrantnegi** [comment]
Waiting.... waiting...
