### ISSUE TITLE
Bug in prompts

### ISSUE THREAD

**Issue by sdras** [sdras/night-owl-vscode-theme#20]
@clarkio mentioned that prompts are not correct, here's a gif:
![2018-05-18_16-17-34](https://user-images.githubusercontent.com/2281088/40259643-4579f0d4-5ab4-11e8-97af-c13da6d7f96a.gif)

**Comment by clarkio** [comment]
Thanks for opening this 🙏 I didn't get around to it at the time

**Comment by sdras** [comment]
No worries! I'm just glad you pointed it out!

**Comment by sdras** [comment]
🎉 awesome!
