### ISSUE TITLE
Update ReadME.md doc for vscode

### ISSUE THREAD

**Issue by AbdulRayhman** [sdras/night-owl-vscode-theme#203]
**Update ReadME.md for VScode users**

I try to separate the editor sidebar by reading the ReadME.md in which I notice when I copy paste the given object in readME.md in the vscode settings the Night Owl with italic color changes apply but when I change my theme to no italic the colors are not applied there. So I changed the "[Night Owl No Italics]" --> "[Night Owl (No Italics)]" the given theme name then its work. Please update the ReadME.md

Thanks!
Happy Coding :)

![Screenshot from 2019-04-25 12-54-59](https://user-images.githubusercontent.com/7883179/56719030-6245c280-6759-11e9-8965-413b251a4526.png)

**Comment by nnnkit** [comment]
Thank You @AbdulRayhman

**Comment by sdras** [comment]
Fixed :)
