### ISSUE TITLE
Wrong colour for string templates

### ISSUE THREAD

**Issue by Kurtz1993** [sdras/night-owl-vscode-theme#205]
I believe that string templates should have the same colour that is used for double-quoted and single-quoted strings 😃 

**Screenshots**
![image](https://user-images.githubusercontent.com/5412470/57089944-426b4d00-6ccb-11e9-9412-e7cc1c109434.png)

**Comment by sdras** [comment]
Keeping them distinct is intentional. Thanks though.

**Comment by Kurtz1993** [comment]
Thanks for the response!
