### ISSUE TITLE
Bold fonts support

### ISSUE THREAD

**Issue by tinvaan** [sdras/night-owl-vscode-theme#208]
This is probably down to personal choice, but I'd really love a "bold" theme option.

I'm happy to attempt a PR for the same, but I want to know if this has this ever been a point of consideration ? If so, what was the resolution ?

**Comment by sdras** [comment]
It hasn't really been a consideration, but for more personal preference styles like this I highly recommend changing your own workplace settings. There's a section in the readme that shows how to do this :) thanks

**Comment by tinvaan** [comment]
Thanks for the update @sdras. I'm sorry if I wasn't clear with my choice of words.

I know `"editor.fontWeight": "bold"` will enable bold fonts on my IDE, but I'm more interested in a bold theme altogether, like the italics variant that is currently on offer.

I'm already using a very hacky version of a bold theme that I scribbled up. Here's a screenshot below
![image](https://user-images.githubusercontent.com/5815030/58380606-ae8e5780-7fd0-11e9-9fc6-13229f2f5d31.png)

I personally like using bold themes and I know many themes provide a bold variant. Night owl provides an italics variant already and hence I was curious to know why there wasn't a bold variant as well.

I think a bold variant would be a great addition to this theme. As mentioned before, I'm happy to attempt a PR :smile:

**Comment by tinvaan** [comment]
*poke* --> @sdras :question:

**Comment by sdras** [comment]
I understood you :) Please reread what I wrote. I don't want to make and maintain a bold theme. I wasn't referring to turning on bold, I was talking about adjusting workplace settings that allow you to make small modifications, as shown in the README. Thanks

**Comment by tinvaan** [comment]
Got it! For the benefit of anyone who maybe wondering what @sdras is referring to, add the relevant customization to the editor's `settings.json` file. Here's an example of a customization that can be used to override theme specific rules : https://github.com/Microsoft/vscode/issues/13092#issuecomment-346064315

As for bold fonts, it's probably a bit more elaborate to achieve the same via `settings.json`, I don't really need it since I have a patch that enables the same through the theme itself.
