### ISSUE TITLE
Text not showing correctly on Tests (Command Palete)

### ISSUE THREAD

**Issue by Arnau-Ninerola** [sdras/night-owl-vscode-theme#223]
I have some unit tests on my python project. Whenever I run the tests on vs code and then I want to see the output, the text is squeezed together on the command palette. If I switch to another theme it works properly.
This bug also happens when I configure my tests to choose what test framework I want to work with.

I included attached screenshots to better understand the problem.
![Annotation 2019-08-20 140410](https://user-images.githubusercontent.com/25803277/63345886-18aa6480-c354-11e9-9f14-4307ffaa5656.png)

Here is the same bug in the configuration of test framework.
![Annotation 2019-08-20 141023](https://user-images.githubusercontent.com/25803277/63346018-64f5a480-c354-11e9-8c20-1baa4724d4f5.png)

And here it's displayed correctly with another theme.
![Annotation 2019-08-20 140443](https://user-images.githubusercontent.com/25803277/63345918-28c24400-c354-11e9-9c61-4f21be35aece.png)

**Comment by sdras** [comment]
Yikes, that's no good. I'll fix it, though I'm low on time so will be at least a month or so. Also open to PRs.

**Comment by Arnau-Ninerola** [comment]
No pressure! I will take a look tho I have never modified any theme
