### ISSUE TITLE
Have been ported to Windows Terminal Color Schemes

### ISSUE THREAD

**Issue by edurojasr** [sdras/night-owl-vscode-theme#224]
Just to let you know that Night and Light Owl's have been ported to Windows Terminal Color Schemes

- Windows Terminal: [https://github.com/edurojasr/Windows_Terminal_Theme_Night_Owl](url)

Love your work! <3

So I took the general color schemas of Night and Light Owl themes and ported to Windows Terminal, Have to tweak some color for the Light version since W. Terminal use white for numbers and I'm thinking of making and other optimization and recommendations for the acrylic feature form Windows Terminal

**Comment by sdras** [comment]
That's awesome! Great thanks! Can you please PR the readme?

**Comment by sdras** [comment]
Nevermind, just did. Thanks!
