### ISSUE TITLE
In Visual Studio 2019 Powershell files color scheme is not readable

### ISSUE THREAD

**Issue by philippedurocher** [sdras/night-owl-vscode-theme#226]
I installed Night Owl yesterday on Visual Studio 2019 Pro edition and really enjoy it! It's a great theme, thank you!

But when working on PS1 files today, I'm having difficulty to read my code due to some dark colors nearly invisibles with the dark background.

![image](https://user-images.githubusercontent.com/1459389/63781165-53ae1a00-c8b7-11e9-8523-e2dcb099f304.png)
![image](https://user-images.githubusercontent.com/1459389/63782378-50b42900-c8b9-11e9-8df6-16dc3cc837de.png)
![image](https://user-images.githubusercontent.com/1459389/63782402-5873cd80-c8b9-11e9-995f-222f84e64316.png)

Thank you for your support!

**Comment by sdras** [comment]
Someone else made the powershell theme, it's not in this repo or maintained by me. Please refile the issue in their repo. Thanks!
