### ISSUE TITLE
Dart Support

### ISSUE THREAD

**Issue by Cascoid** [sdras/night-owl-vscode-theme#229]
Dart is a programming language raising in popularity thanks to Flutter, google's cross platform mobile development solution.

Unfortunately, when using the Night Owl theme, the colours it tries to provide are majority green.

Example: 
![image](https://user-images.githubusercontent.com/5270745/64111408-8905ac80-cd7c-11e9-9186-677e1c6aed3e.png)
Here is an example of a theme which supports dart (material theme):
![image](https://user-images.githubusercontent.com/5270745/64111474-b5212d80-cd7c-11e9-8ca0-3dc0a4086071.png)

As you can see, Night Owl seems to throw green at everything. It also puts things like null, true and false in blue which in other languages you've got it as red. It would be great if support for Dart was a thing.

**Comment by sdras** [comment]
As mentioned in the readme, please PR the demo repo if you would like to request language support. Thanks!

**Comment by Cascoid** [comment]
Don't know how I missed this notification - seems it's already being sorted out in commit #234 

Closing!
