### ISSUE TITLE
`this` keyword color

### ISSUE THREAD

**Issue by Miloshinjo** [sdras/night-owl-vscode-theme#242]
In many themes, the `this` keyword stands out when typed, but in Night Owl (which is my favorite), the this keyword is the same color as the next 'line of code' (this.constructor.calcAge() --- `this` and `constructor` would be the same color.

Is it possible to make the `this` keyword RED like booleans are red in the theme? I can also try to do it myself if permission granted and idea is accepted.

**Comment by mmahandev** [comment]
Would be an amazing change. How do other themes do this?

**Comment by ismet** [comment]
Totally agree.. But the boolean RED might be confusing, a different (softer?) color would be great!

**Comment by sdras** [comment]
So, I spent a while working on this. I completely see what you're saying, unfortunately running into a bit of an "if everything is important, nothing is" problem. I updated the color to stand out much more, tested with some a11y filters. Contrast should be much better without breaking the color theme overall. Let me know what you think, cutting a release soon.
