### ISSUE TITLE
Odd neon green for variable names

### ISSUE THREAD

**Issue by dominictwlee** [sdras/night-owl-vscode-theme#248]
vscode: v1.4.3
theme: v1.1.3

**Screenshots**
![image](https://user-images.githubusercontent.com/34794189/76404515-82d13800-637e-11ea-9939-a3d60d3047d1.png)
![image](https://user-images.githubusercontent.com/34794189/76404728-dc396700-637e-11ea-9117-0e0fd6bd5b74.png)

I noticed that all variables are now a neon green/yellow. Is this recent change intentional or a bug? Seems a bit jarring since they were mainly used for props and now are showing everywhere, including imports.

**Comment by burdell** [comment]
Noticed this as well and did some research and looks like it might be related to this: https://github.com/microsoft/vscode/issues/92308. Apparently VS Code introduced a new semantic highlighting system

Turning it off like this comment suggests worked for me until the theme itself can be updated https://github.com/microsoft/vscode/issues/92308#issuecomment-596885893

**Comment by dominictwlee** [comment]
Cool that works, thanks @burdell !

**Comment by aeschli** [comment]
marking as duplicate of #92308
