### ISSUE TITLE
HTML tag opening & closing mark

### ISSUE THREAD

**Issue by marpme** [sdras/night-owl-vscode-theme#25]
I would also add that, react (HTML) tags aren't marked like functions and objects are.

React HTML tags

<img width="836" alt="grafik" src="https://user-images.githubusercontent.com/7430964/40272150-7dd13cee-5ba9-11e8-9a4b-14860da63f5e.png">

**VS** 

Function marker

<img width="493" alt="grafik" src="https://user-images.githubusercontent.com/7430964/40272154-8c79af4c-5ba9-11e8-9c7f-2087dd932cd7.png">

Would love to see such a thing for HTML tags in general as well! 
Great work so far!

**Comment by sdras** [comment]
Hi! Thanks for visiting.

Can you please elaborate? AFAICT, `getMonthlyIncomeFormatted` is the same in both, the `XVGFormatter` is the same in both, `this` keyword is the same in both, the method `.format` is the same... 

To explain a little more in depth where I'm coming from, I'm looking for:
- consistency in meaning
- contrast in same-line usage for red/green deficient colorblindness
- general contrast

Thanks!

**Comment by sdras** [comment]
Hm, I'm not sure I'm into it- can you please show me another theme that does this? Then I can tell how the legibility is and also how to target if it's possible.

**Comment by sdras** [comment]
Hi! I did some research and that's applied through VS Code, it's not a setting for a theme that I can create. If you're unhappy with it, you can report in their repo, but there'sn not much I can do on my end. Thanks!
