### ISSUE TITLE
Colors are different in my VSCode

### ISSUE THREAD

**Issue by MiguelMachado-dev** [sdras/night-owl-vscode-theme#250]
The color theme is different, it was not those colors before

**Screenshots**
![image](https://user-images.githubusercontent.com/29252011/76524856-8ed5fc00-6449-11ea-8c61-82958b37b54d.png)

Here is my settings and extensions
https://gist.github.com/MiguelMachado-dev/f34532c34f5b001c7e10ebe8592b0193

I'm going to link the gist because it is a little extense

**Comment by jvbianchi** [comment]
Have you tried to set your settings:

`editor.semanticHighlighting.enabled": false`

**Comment by MiguelMachado-dev** [comment]
@jvbianchi this actually worked! I have no idea why this changed in a day to another
Thanks

**Comment by MiguelMachado-dev** [comment]
I never had to set this, doesn't even know this exists
