### ISSUE TITLE
Green tokens in JavaScript file? 

### ISSUE THREAD

**Issue by zellwk** [sdras/night-owl-vscode-theme#251]
I noticed the blue tokens changed to green (after startup) today in my JavaScript file. Is this intentional? Is there a bug somewhere? Or does this only happen to me? 

![green tokens](https://user-images.githubusercontent.com/3607637/76609554-89180d80-6552-11ea-9c8e-08dda7ea0929.gif)

Just wanted to make sure so I'm asking. 

Thanks!

**Comment by StormriderX** [comment]
This happened to me after vs code update. I am interested in a fix too

**Comment by sdras** [comment]
This is breaking due to a change in VS Code, as @StormriderX mentioned. I have some stuff going on but will put in a patch soon :)

**Comment by duerdod** [comment]
> Uncheck this
> ![Capture](https://user-images.githubusercontent.com/50478258/76624387-de95ef80-653d-11ea-8a6e-3b188e4f628a.PNG)

This works for now! Thanks!

**Comment by sdras** [comment]
Seems they made an update to make this less aggressive- can anyone tell me if even without this checked it looks back to normal? It looks back to normal for me. I think eventually they'll require some rewrite though.

**Comment by zellwk** [comment]
@sdras I'm still seeing thing in the GIF I posted. Are you on Insiders? Maybe the patch hasn't made it to the normal VSCode version? 🤔

**Comment by sdras** [comment]
I've tried to set semantic highlighting to false and make some changes- can you please update and let me know if it's better? Thanks!

**Comment by sdras** [comment]
This should be fixed by upstream changes now.

**Comment by zellwk** [comment]
Sorry I completely forgot to check the semantic highlighting issue previously!

**Comment by sdras** [comment]
No worries Zell! ✌️
