### ISSUE TITLE
Adopt semantic highlighting

### ISSUE THREAD

**Issue by aeschli** [sdras/night-owl-vscode-theme#255]
Since 1.43, VSCode themes can take advantage of [semantic highlighting](https://code.visualstudio.com/docs/getstarted/themes#_semantic-highlighting).

Every theme controls whether semantic tokens are enabled. So far, only built-in themes have it enabled and I filed this issue to ask you to opt-in for the Night Owl themes as well.

Adoption is easy and there are new cool styling possibilities.

To turn on semantic highlighting for a theme, all you have to do is put
`"semanticHighlighting": true`
in the theme's definition file.

There's a good chance that no further change to the theme is needed (thanks to a default mapping from semantic tokens to TextMate scopes (if not, I'd be interested to know, so I can improve the defaults further)). 

But, more interestingly, themes can tune and go wild by defining new styling rules against the semantic tokens:
```json
"semanticTokenColors": {
    "variable.readonly": "#ff0000", 
    "parameter": { "fontStyle": "underline" },
    "*.declaration:java": { "fontStyle": "bold" }
} 
```

Check out our [Semantic Highlighting Wiki](https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview) and the [Semantic Highlighting Guide](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) for more details and feel free to ping me in this issue if I can help.

Thanks for the great work and looking forward to semantic highlighting in your theme.

**Comment by abhijithvijayan** [comment]
Thanks for highlighting this issue.

**Comment by sdras** [comment]
Sorry, semantic highlighting completely destroyed this theme. I've opted out, I'm not even sure if that restored it.
