### ISSUE TITLE
JSX: Wrong highlight colors

### ISSUE THREAD

**Issue by manu810** [sdras/night-owl-vscode-theme#256]
Hello,

I'm pretty sure I'm the one doing something wrong, but I can't manage to have JSX highlighted as on the theme screenshots, especially React component names that are green instead of orange.

Expected:
![nightOwl_expected](https://user-images.githubusercontent.com/18647279/80486300-3906d600-895b-11ea-8985-3862a5d2717b.png)

Actual:
![nightOwl_actual](https://user-images.githubusercontent.com/18647279/80486327-4328d480-895b-11ea-968e-cd60d793e425.png)

Has anyone already been confronted to this?

Thank you

**Comment by wab** [comment]
same issue here, still searching

**Comment by wab** [comment]
it seems to come from this extension
https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel

**Comment by wab** [comment]
but without extension, styled-components are difficult to read
![image](https://user-images.githubusercontent.com/341980/81552521-eaf2c900-9383-11ea-9ffc-2d795c46fedd.png)

**Comment by manu810** [comment]
Thanks a lot for sharing this info wab! Disabling this extension worked for me.

**Comment by sdras** [comment]
Thanks! I'll put a note in the readme about this

**Comment by sdras** [comment]
Added to README
