### ISSUE TITLE
Homepage text not visible

### ISSUE THREAD

**Issue by Hassan0x00A** [sdras/night-owl-vscode-theme#264]
**Screenshots**
![Other themes](https://user-images.githubusercontent.com/43752364/87680148-58a0e400-c77d-11ea-80dd-7ef9321d006f.png)
![Night Owl](https://user-images.githubusercontent.com/43752364/87680161-5d659800-c77d-11ea-92f7-dd63b1104698.png)

The text below the VSCode Logo isn't visible with the Night Owl Theme

**Comment by sdras** [comment]
Interesting, thanks for letting me know

**Comment by sdras** [comment]
This was an upstream change in vs code that has since been fixed, thank you for the issue
