### ISSUE TITLE
Theme syntax colors change with Powershell semantic highlighting enabled

### ISSUE THREAD

**Issue by IvanDrag0** [sdras/night-owl-vscode-theme#269]
When using the VS Code powershell extension with the semantic highlighting enabled, the Night Owl theme changes syntax colors.

Semantic highlighting disabled:

![semanticHighlighting disabled](https://user-images.githubusercontent.com/24702285/93112187-4d830b00-f67d-11ea-9860-6c19e370db21.png)

Semantic highlighting enabled:

![semanticHighlighting enabled](https://user-images.githubusercontent.com/24702285/93112214-54aa1900-f67d-11ea-9ee9-3802b2b4a017.png)

**Comment by sdras** [comment]
I tried to turn semantic highlighting off, it completely ruined this theme. Please update and let me know if it's better.

**Comment by MiguelMachado-dev** [comment]
@sdras do you use it true or false?

**Comment by sdras** [comment]
This was fixed upstream, it was an issue in VS Code
