### ISSUE TITLE
Suggestion: don't emphasize nested square brackets

### ISSUE THREAD

**Issue by emilio-martinez** [sdras/night-owl-vscode-theme#27]
I was testing out your theme (thank you!) while writing some tests 🔬and saw this use case which I _personally_ found offputting, so I thought I'd bring it up:

Nested square brackets are italicized which particularly looks kind of funny when juxtaposed against other kinds of brackets, e.g., curly, as shown below.

![code](https://user-images.githubusercontent.com/9163179/40274244-083d2aa0-5b87-11e8-9041-e44694460234.png)

I don't know if it's by design or not, but in any case, I thought I'd just put it out there. Plus, I realize it can easily be disabled in settings. Thank you for your work!

**Comment by sdras** [comment]
Oh yeah that's a bug on my part, it's an inheritance failure I just had to fix with arrow functions. Thanks for pointing it out! I'll try to get this done soon.

**Comment by sdras** [comment]
This should be fixed! Please reload!
