### ISSUE TITLE
Comment color customization does not fully apply

### ISSUE THREAD

**Issue by norentkhy** [sdras/night-owl-vscode-theme#272]
Good day,

When I use the following in `settings.json`
```
  "editor.tokenColorCustomizations": {
    "comments": "#fff30f"
  },
```
I get
![image](https://user-images.githubusercontent.com/60198834/95609196-a2d4f100-0a5e-11eb-8d07-9e3334745c9b.png)
Instead of (sample theme: "One Dark (Sublime)")
![image](https://user-images.githubusercontent.com/60198834/95609424-f3e4e500-0a5e-11eb-87a0-72c88b882e55.png)
Am I missing an extra token color customization?

Thanks!

**Comment by sdras** [comment]
This should do it:

```
 "editor.tokenColors": {
    "comments": "#fff30f"
  },
```

**Comment by norentkhy** [comment]
It didn't do the trick for me.

**Comment by norentkhy** [comment]
I figured it out:
```
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "name": "Double-Slashed Comment",
        "scope": "comment.line.double-slash",
        "settings": {
          "foreground": "#fff30f"
        }
      }
    ]
  },
```

**Comment by norentkhy** [comment]
Btw, thank you for making this theme :-)
