### ISSUE TITLE
Some Vue object clarity

### ISSUE THREAD

**Issue by mikeerickson** [sdras/night-owl-vscode-theme#273]
I am looking to get a little better visual of `Vue` objects.  Is it possible to customize the color for the italic (_`company`_) portion in the following screenshot

![image](https://user-images.githubusercontent.com/183153/95778381-ddb47000-0c7c-11eb-806f-49a266e303db.png)

**Comment by sdras** [comment]
I think this should be better in the new release, please feel free to reopen if not!

**Comment by mikeerickson** [comment]
Hey Sarah

It is definitely different and more distinguishable.  Is this the intended color(s):

- The table portion is same color
- The field portion is white

![image](https://user-images.githubusercontent.com/183153/95923702-eaaf8d00-0d6a-11eb-979d-41f257a5f7e8.png)
