### ISSUE TITLE
I don't know if its a bug with html coloring tags

### ISSUE THREAD

**Issue by leucioiustefan** [sdras/night-owl-vscode-theme#276]
Hello! I've recently noticed that html tag colors are more white than before, they used to be a light blue color. 
![Html](https://user-images.githubusercontent.com/50478258/96851072-47443380-1460-11eb-896d-aa0f29f59b36.PNG)
My eyes do not discern a difference between the tags color and the content between them. Is this what it should look like?
Html tag color looked like this.
![tag color](https://user-images.githubusercontent.com/50478258/96851308-8d00fc00-1460-11eb-8201-cee72f1fcb9f.PNG)

**Comment by leucioiustefan** [comment]
Also I see a problem here.
![Problem](https://user-images.githubusercontent.com/50478258/96852109-6becdb00-1461-11eb-9ddf-de937d79f538.PNG)
It says it expects an object.

**Comment by mattfwood** [comment]
I've started seeing the same thing, i believe it happened when I updated VS code and it's due to a change in this theme. I'm still trying to figure out if there's a setting to revert this. I'll post back if i have any luck

**Comment by mattfwood** [comment]
Got it! So if you go to your `settings.json` and add this, it should revert the HTML tags to how they looked previously:

```json
  "editor.tokenColorCustomizations":{
    "textMateRules":[
      {
        "scope":[
          "entity.name.tag",
          "meta.tag.other.html",
          "meta.tag.other.js",
          "meta.tag.other.tsx",
          "entity.name.tag.tsx",
          "entity.name.tag.js",
          "entity.name.tag",
          "meta.tag.js",
          "meta.tag.tsx",
          "meta.tag.html"
        ],
        "settings":{
          "foreground":"#7FDBCA"
        }
      }
    ]
  }
```

![image](https://user-images.githubusercontent.com/22530815/96930840-f9d8be00-1481-11eb-8ca3-72a499dae0a2.png)

**Comment by leucioiustefan** [comment]
For me it says Property "textMateRules" is not allowed

**Comment by leucioiustefan** [comment]
Thank you!
