### ISSUE TITLE
powershell console support

### ISSUE THREAD

**Issue by khoshroomahdi** [sdras/night-owl-vscode-theme#277]
**Describe the solution you'd like**
i would like to have nightowl schema for powershell color scheme.
i could set nightowl for windows terminal but it do nothing to powershell color scheme. 
i mean ex: variable color, command color and ...
--------
get-psreadlineoption
![1](https://user-images.githubusercontent.com/20259070/97152856-c9956600-1786-11eb-9fe9-6af4f52b24de.jpg)

**Comment by ivansvlv** [comment]
@khoshroomahdi hey 👋🏻 this is a repository for the VS Code theme. Have you tried this one? - https://github.com/edurojasr/Windows-Terminal-Theme-Night-Owl

**Comment by khoshroomahdi** [comment]
Yes. I tried.

**Comment by sdras** [comment]
Hey there! As @ivansvlv mentioned, this project is scoped for VS Code not Windows Terminal. The palette is in the theme's JSON if you want to create one and you don't like that existing one, though. Thanks!
