### ISSUE TITLE
Visual cue needed for separation between the editor and the explorer

### ISSUE THREAD

**Issue by astronomersiva** [sdras/night-owl-vscode-theme#28]
Thanks for working on this great theme! I am loving it.

I would like to suggest adding a border between the editor and the explorer or have a different background color for the explorer to provide a nice separation.

**Comment by markvdesign** [comment]
I agree, some colour separation would be very nice. I actually used this for the sidebar
`"sideBar.background": "#000a13",`
`"sideBar.border": "#262a39",`
I think these look nice.

**Comment by sdras** [comment]
Done!
