### ISSUE TITLE
color blind people issue

### ISSUE THREAD

**Issue by ghost** [sdras/night-owl-vscode-theme#280]
**Some colors are too close to each other  and this make color recognition harder for color blinded people**

**Screenshots**
![image](https://user-images.githubusercontent.com/42757613/100698180-146d5380-33ad-11eb-9efd-f729e7cb5113.png)

It's great theme and I'm waiting for it to get better
Thanks for considering color blinded night owls!

**Comment by caseybaggz** [comment]
Second this. The one thing I have a problem with (pretty major), is the background-highlighted color. I can barely see it. 😭

**Comment by caseybaggz** [comment]
I was able to adjust the theme in my VSCode settings by adding the below to the `settings.json` file:
```
"workbench.colorCustomizations": {
    "[Night Owl]": {
      "list.focusBackground": "#2E3250"
    }
  }
```
I just tried to find the color that was used elsewhere in the theme so it didn't feel out of place. It was honestly still hard for me though since I don't see some of these colors well. 🙈

**Comment by sdras** [comment]
Cutting a release today that should help with the focus background issue.
