### ISSUE TITLE
Night Owl theme is either overriding or not specifying default markup textMateRules #57 #105

### ISSUE THREAD

**Issue by smcenlly** [sdras/night-owl-vscode-theme#283]
**Describe the bug**
Theme is either overriding or not specifying default markup `textMateRules` that are provided with VS Code default themes. This breaks syntax highlighting in extensions that use these rules.

**To Reproduce**
1. Clone [https://github.com/smcenlly/missing-textmate-tokens](https://github.com/smcenlly/missing-textmate-tokens) VS Code sample extension.
2. Open the repo and run `npm install`
3. Open the repo in VS Code and Start debugging (F5).
4. Create a new file (Ctrl + N).
5. Change its language to markup using the Change Language Mode command
6. Paste the contents below:

```
deleted

inserted

underline
```

7. Using any of the VS Code themes, you will see output similar to:
![Working Example](https://github.com/smcenlly/missing-textmate-tokens/raw/main/working.png)

**Expected behavior**
Theme should provide similar formatting (adjusted to its themes). Instead, no highlighting is displayed.

![image](https://user-images.githubusercontent.com/2074089/106074656-fa0ae880-6157-11eb-9db4-7ea5c7de7a4c.png)

**Comment by smcenlly** [comment]
Bumping this issue - any plans to fix?

**Comment by sdras** [comment]
Added this in, thank you for the example repo. There's no way to check the language in settings anymore. Cutting a release today.
