### ISSUE TITLE
Inconsistent `const` keyword highlighting (JavaScript/TypeScript)

### ISSUE THREAD

**Issue by ebxn** [sdras/night-owl-vscode-theme#289]
**Please make sure you're using the latest version of the plugin before submitting an issue**
Using v2.0.0, set to "Night Owl".

**Screenshots**
![image](https://user-images.githubusercontent.com/32674127/118337270-5af1dd00-b50b-11eb-8695-778baed025f3.png)

As you can see in the screenshot, the `const` keyword is correctly highlighted pink in a normal context, but becomes blue when it's inside an object using the ES2015 shorthand method name syntax.

This is similar to, but a different context from, #237.

Thanks!

**Comment by defytheflow** [comment]
@ebxn, try adding these to your settings.json

```json
  "editor.tokenColorCustomizations": {
    "[Night Owl][Night Owl (No Italics)]": {
      "textMateRules": [
        {
          "scope": [
            "meta.object.member.ts meta.var.expr.ts storage.type.ts",
            "meta.object.member.tsx meta.var.expr.tsx storage.type.tsx",
            "meta.objectliteral.ts meta.var.expr.tsx storage.type.tsx",
            "meta.objectliteral.tsx meta.var.expr.tsx storage.type.tsx"
          ],
          "settings": {
            "foreground": "#C792EA"
          }
        }
      ]
    }
  },

```

**Comment by ebxn** [comment]
Hiya @defytheflow,

Thanks for your response! I regret to inform you that it doesn't seem to have worked in this instance :(

You can find my VSCode settings [here](https://pastebin.com/0uuMPrYP).

![image](https://user-images.githubusercontent.com/32674127/184497923-eff1dd62-e2f4-4b6f-ac46-f5c79b7c4c48.png)

**Comment by ebxn** [comment]
Hiya @defytheflow,

Thanks for your response! I regret to inform you that it doesn't seem to have worked in this instance :(

You can find my VSCode settings [here](https://pastebin.com/2aVM7a1F).

![image](https://user-images.githubusercontent.com/32674127/184497987-0ee2ab88-96a0-44bf-b818-fc4096a84f97.png)

**Comment by defytheflow** [comment]
@ebx,
My bad, the third string in the scope array must have a .ts extension at the end of every scope. I've edited my answer, try now.

**Comment by ebxn** [comment]
Hey @defytheflow,

Sorry for the slow response. I can confirm your solution works!

Thanks very much for the help.

![image](https://user-images.githubusercontent.com/32674127/184898422-1e5cef12-345e-4e02-b8e3-458484220a7d.png)
