### ISSUE TITLE
Suggestion: React element and HTML element colors in JSX

### ISSUE THREAD

**Issue by alexluong** [sdras/night-owl-vscode-theme#29]
Thank you for the great theme. I just wanna bring up one suggestion: when writing JSX, React elements and HTML elements have the same tag color:

Night Owl:

![nightowl](https://user-images.githubusercontent.com/26750127/40288488-1591a2a6-5c79-11e8-868c-8b5560bcad36.png)

whereas in Material Theme Ocean:

![material](https://user-images.githubusercontent.com/26750127/40288523-3d7cc638-5c79-11e8-937f-1ff914af6a1b.png)

I'm not sure if the design is intentional. Having separate colors helps me when writing JSX. I hope you can consider implementing this in the future or help guide me to tweak this myself. Thanks.

**Comment by sdras** [comment]
Interesting, that was actually an intentional decision but I think you're right. Let me ask a few other people to get a consensus and then I'll get back to you!
