### ISSUE TITLE
Variable color is changed at read and write.

### ISSUE THREAD

**Issue by sivakumargsk** [sdras/night-owl-vscode-theme#290]
Hello Everyone,

* Variable color is changed at read and write and also it uses same color for parameters as result its little harder to differentiate both.
* Keywords and constants are also having same color. 

<img width="799" alt="Screen Shot 2021-05-31 at 12 52 38 AM" src="https://user-images.githubusercontent.com/13914029/120117622-b1b61280-c1ab-11eb-86c2-73f65a8c5175.png">

**Comment by sdras** [comment]
Thanks for the issue, and the screenshot. This is because one is a declaration and the other is in usage, this was a feature that was requested.
