### ISSUE TITLE
Mapping custom color definition into vscode color definition

### ISSUE THREAD

**Issue by ghost** [sdras/night-owl-vscode-theme#291]
**Describe the solution you'd like**
I want to map this custom color definition into vscode night owl color definition
```
 {
    id: "night-owl",
    name: "Night Owl",
    highlights: {
      background: "#011627",
      text: "#abb2bf",
      variable: "#82AAFF",
      attribute: "#F78C6C",
      definition: "#82AAFF",
      keyword: "#c792ea",
      operator: "#c792ea",
      property: "#fff",
      number: "#F78C6C",
      string: "#ecc48d",
      comment: "#717a8a",
      meta: "#7fdbca",
      tag: "#7fdbca",
    },
  },
```

**Is your feature request related to a problem? Please describe.**
I want to use these color definitions in my vscode (with Night Owl theme installed)
but I don't know how to map these into vscode settings.json
Hope that you lot can help me

**Comment by sdras** [comment]
Hi, thanks for the issue. The colors used in this theme are intentional, so I won't be altering these.
