### ISSUE TITLE
React Components not displayed in orange color on MacOS

### ISSUE THREAD

**Issue by Marko721** [sdras/night-owl-vscode-theme#295]
Mac:
![mac](https://user-images.githubusercontent.com/51479266/132076735-8364d125-5533-4478-8304-bb5c9c101f86.JPG)
Windows:
![windows](https://user-images.githubusercontent.com/51479266/132076740-07ef1f85-e05a-48f4-82c0-16f517e9dd9c.png)

**Comment by Raj2631** [comment]
Hey there, I have a similar issue(I use  windows though)! The color of the component in JSX is same as the green in props, also the color when you destructure props has changed as well. And the color for object's property has changed as well.
Screenshots below ⬇
![image](https://user-images.githubusercontent.com/43057108/132940087-83546cf2-e15e-4949-b31c-205fb4c0f53b.png)
![image](https://user-images.githubusercontent.com/43057108/132940158-03e20e79-0fc7-472b-a1ff-b94cc6b3a8e1.png)

**Comment by Marko721** [comment]
Indeed the babel extension was the problem. Thank you
