### ISSUE TITLE
Can’t distinguish which tab is currently selected in the tab bar

### ISSUE THREAD

**Issue by bryanjclark** [sdras/night-owl-vscode-theme#3]
Thanks so much for sharing this theme!

One bug that stood out: I can’t tell which tab is selected by the color palette (see attached image)

![screenshot of tabs](https://user-images.githubusercontent.com/868389/40206820-84aeb1a0-59e6-11e8-8b23-d25768c64f5f.png)

**Comment by stevehollaar** [comment]
Thanks @sdras for this theme, looks great!

Related to this I think, the contrast of the tabs in inactive panes drops to difficult-to-read levels
<img width="461" alt="screen shot 2018-05-17 at 3 25 57 pm" src="https://user-images.githubusercontent.com/918252/40206899-bfbe8f0e-59e6-11e8-9192-c82f159ba527.png">

**Comment by sdras** [comment]
Thank you for reporting! I'll work on this right away

**Comment by codinronan** [comment]
Came here to say this :) Love the theme though!!

**Comment by sdras** [comment]
Thanks everyone! This is now updated. Please update to the new release! Feel free to reopen if I missed something :)
