### ISSUE TITLE
Highlighted text in Peek Declaration list is the same color as the background

### ISSUE THREAD

**Issue by Robo210** [sdras/night-owl-vscode-theme#30]
Right-click on a symbol and select Peek Declaration. The highlighted text in the list of results has no contrast against the background. (Peek Declaration may be specific to the C/C++ extension when Intellisense is configured for the project. I can provide whatever you need if you don't have code where this shows up.)

Night Owl:
![nightowl](https://user-images.githubusercontent.com/1312684/40290736-e3738cc0-5c74-11e8-89d3-ef1d06d5cfc3.png)

Dark+ (Default):
![default_dark](https://user-images.githubusercontent.com/1312684/40290738-ebb4b67a-5c74-11e8-9d10-9915578fc282.png)

**Comment by sdras** [comment]
@lauragift21 fixed this! Thank you Gift.
