### ISSUE TITLE
The splitting line between two editors are imperceptible/invisible.

### ISSUE THREAD

**Issue by zzeitt** [sdras/night-owl-vscode-theme#301]
When I split editor windows horizontally or vertically, the splitting lines between windows are hard to be distinguished from background color.

|Screenshots       |
|----------- |
|![cur][cur]current screenshot |
|![hor][hor]where the horizontal splitting line should be |
|![ver][ver]where the vertical splitting line should be |

[cur]:https://user-images.githubusercontent.com/30381410/147093917-d8d57e69-0f3d-4987-ac2a-6ff8cd965d12.png
[hor]: https://user-images.githubusercontent.com/30381410/147094974-3ba4910b-afa8-42d1-9be3-cff2a8b7ab87.png
[ver]: https://user-images.githubusercontent.com/30381410/147094984-30c428ff-eb33-4fce-9460-e8de2aaf1a76.png

**Comment by gambolputty** [comment]
This can be changed with the `sash.hoverBorder` setting ([docs](https://code.visualstudio.com/api/references/theme-color#base-colors)). For example:

```json
"workbench.colorCustomizations": {
  "sash.hoverBorder": "#285888"
}
```

**Comment by zzeitt** [comment]
Thanks for pointing me to the right direction, though what I want is to change the color of the border, without hovering.

This is how I finally got it to work,
```json
 "workbench.colorCustomizations": {
        "editorGroup.border": "#24333f",
    }
```
And if you want to change other imperceptible borders, I have found the configurations:
```json
 "workbench.colorCustomizations": {
        "activityBar.border": "#24333f",
        "sideBar.border": "#24333f",
        "editorGroup.border": "#24333f",
        "titleBar.border": "#24333f",
    }
```
|Before | After |
|---|---|
|![image](https://user-images.githubusercontent.com/30381410/182808527-579098c9-21f3-46de-bd7f-fa31990e4794.png)|![image](https://user-images.githubusercontent.com/30381410/182808855-ad4a330f-9926-4edb-879c-29f3c9131e2e.png)|

**Comment by zzeitt** [comment]
I just found that it has been stated in README (https://github.com/sdras/night-owl-vscode-theme#separate-the-editor-from-the-sidebar) 😂……
