### ISSUE TITLE
diffeditor borders are visually disruptive

### ISSUE THREAD

**Issue by xmatthias** [sdras/night-owl-vscode-theme#304]
**Screenshots**
the (quite bright) borders between the lines make it quite difficult to concentrate on the diff lines itself, when it's a diff of more than 2 lines.

![image](https://user-images.githubusercontent.com/5024695/150633706-d3f853f5-be82-4f3f-8ea1-88f5b015e890.png)

The borders themselfs are caused by `diffEditor.insertedTextBorder` and `diffEditor.removedTextBorder` - however setting them to transparent (or any other color) will only make them stand out less, not remove them completely (i suspect it's something in vscode that causes this overlap if border-properties are set).

The only way i found to get rid of them is to edit the original file (in my case `~/.vscode/extensions/sdras.night-owl-2.0.1/themes/Night\ Owl-color-theme.json`), and remove these attributes from the file (colorCustomizations don't seem to allow unsetting these properties).

The result will look as follows - which i think is a lot less intrusive, and makes the text/diff stand out a lot more.

![image](https://user-images.githubusercontent.com/5024695/150633809-be236611-0161-48b6-aff0-5edd93f513e1.png)

If desired, i can make a PR removing this (i feel this small change will make this Theme perfect).

**Comment by alxgnon** [comment]
Thanks, I was also wondering how to fix this, as the thick lines in the diff editor are quite annoying and ugly. I hope this change makes it into the theme, as it is much better like this.

**Comment by brianmoran** [comment]
You should open a PR for this! I stopped using this theme because of this issue. Thanks for figuring it out.

**Comment by sdras** [comment]
This is merged, cutting a release now that should fix
