### ISSUE TITLE
Bracket pair colors

### ISSUE THREAD

**Issue by LmarLoe** [sdras/night-owl-vscode-theme#305]
Since the Bracket Pair Colorizer has been deprecated in favor of native functionality,
the color of the third nested brackets is different from what it used to be with the extension.
I suggest bring back this color (#87CEFA) because it is more distinguishable by colorblind people.

**Comment by andreluis-oliveira** [comment]
this theme is not developed for colorblind.

If you want to customize colors, you can do it by overriding your theme ( settings.json ).

"workbench.colorCustomizations": {
    "editorBracketHighlight.foreground3": "#87CEFA"
}

**Comment by sdras** [comment]
This theme *is* developed for colorblind, a lot of testing was done, and I wrote a post explaining this, linked in the readme.

Thanks for the issue @LmarLoe, I will look into this today.

**Comment by sdras** [comment]
Fixed
