### ISSUE TITLE
Code Hints in C# in VS 2022 are unreadable on this theme

### ISSUE THREAD

**Issue by keyable** [sdras/night-owl-vscode-theme#314]
The code hints in C# in VS 2022 look too bright and they are unreadable. Please have a look at screenshot.

![image](https://user-images.githubusercontent.com/65192114/191322216-efa7eec8-d906-423e-9a20-e33dc34fef2e.png)

**Comment by SumitKar01** [comment]
Hey there I have a fork of NightOwl for VS 2022. I would like to know if the fork works for you.
https://github.com/SumitKar01/NightOwl-Theme-VS-2022

**Comment by SumitKar01** [comment]
@keyable Here is how it looks
![image](https://github.com/sdras/night-owl-vscode-theme/assets/73392533/5ee8b644-2cf9-4ff8-8941-040cae90e868)
