### ISSUE TITLE
Inconsistent Italics when returning JSX

### ISSUE THREAD

**Issue by mohammedyh** [sdras/night-owl-vscode-theme#317]
I noticed when returning JSX using the `function` keyword and using the function expression syntax, the function expression syntax, for some reason, italicizes the text whereas the `function` syntax does not.
(Using latest version - 2.0.1)

**Screenshot**
![CleanShot 2022-12-26 at 21 49 49@2x](https://user-images.githubusercontent.com/32526267/209585294-9b66e89d-c81d-4f0d-ac9a-695c6ee8c80b.png)

**Comment by sdras** [comment]
Hey there! Thanks for filing this. This is actually the intended behavior (this theme maximizes small differences in order to provide a lot of contrast. I have a no italics version if it bothers you.
