### ISSUE TITLE
Reduce specificity of selectors

### ISSUE THREAD

**Issue by kentcdodds** [sdras/night-owl-vscode-theme#319]
**Please make sure you're using the latest version of the plugin before submitting an issue** ✅

**Screenshots**

![227631785-8b0f2c70-a168-44e6-bc15-defcc3803930](https://user-images.githubusercontent.com/1500684/228455757-b9db9f24-31c3-46f9-a6f7-1e71c481b41f.png)

When working in an `.mdx` file with the latest mdx highlighter, I'm no longer getting highlights for several things which the maintainer of the mdx language highlighter is [telling me](https://github.com/wooorm/markdown-tm-language/issues/1#issuecomment-1483806853) is due to Night Owl being overly specific in its selectors:

> And that’s where we find a very important bug in Night Owl:
> 
> * Here’s [what we expose](https://github.com/wooorm/markdown-tm-language/blob/37c75fa6ffe72dc42c5a5a340feb431dc77616b8/grammar.yml#LL542C16-L542C16): `markup.heading.atx.1.mdx`
> * Here’s [what VS Code Solarized selects](https://github.com/microsoft/vscode/blob/bf9141ba2358054beabd811b1c79bc46b5163bda/extensions/theme-solarized-dark/themes/solarized-dark-color-theme.json#L312): `markup.heading`
> * Here’s [what Night Owl selects](https://github.com/sdras/night-owl-vscode-theme/blob/f260cea5356261337d18809bdbe922952c7a6fa4/themes/Night%20Owl-color-theme-noitalic.json#L1403): `markup.heading.markdown`
> 
> Looking at almost all scopes in Night Owl, they are super specific. Specific to JS, or to JSX, or to markdown. And they’re not supposed to be like that, they’re supposed to as vague as possible (`markdup.heading`), unless you really need to differentiate `markup.heading.markdown` from others (e.g. `markup.heading.html`) or so.
> 
> So that’s where a lot of the problems come from!
> 
> #### Inline code
> * GitHub : `markup.raw`
> * VS Code Solarized: `markup.inline.raw`
> * VS Code Night Owl: `markup.inline.raw.markdown`
> 
> I think this is a weird choice in VS Code themes to go with `markup.inline.raw`. `markup.raw.inline` makes more sense, then you can also have `markup.raw.block`. But I’ve just pushed the name VS Code uses: [60fa64b](https://github.com/wooorm/markdown-tm-language/commit/60fa64b6a598576b2493905f506f9bf1580d156a). Note that Night Owl still should drop the `.markdown` suffix.

That last comment is the suggestion:

> Night Owl still should drop the `.markdown` suffix.

Could we do that?

**Comment by andreluis-oliveira** [comment]
@kentcdodds  PR to fix support to mdx files.

Before:
![before](https://user-images.githubusercontent.com/53203742/235248108-6933b22b-377f-4417-995a-1a0bf5edb3ba.jpg)

After:
![after](https://user-images.githubusercontent.com/53203742/235247772-67f6fb6e-1baa-4af1-bdbb-96f4500796f7.jpg)

**Comment by sdras** [comment]
This is merged, will cut a release today.
