### ISSUE TITLE
[Version 2.1.0, Light] - changes to braces colors makes some braces hard to see

### ISSUE THREAD

**Issue by orept** [sdras/night-owl-vscode-theme#331]
**2.0.2**: (Normal)
<img width="476" alt="night-owl-pre-2 1" src="https://github.com/user-attachments/assets/9a0600c5-0134-4e35-abc5-80fe01721bb3" />

**2.1.0**: (Bad)
<img width="474" alt="night-owl-2 1-bad-color" src="https://github.com/user-attachments/assets/5aaebbc6-a6e8-4ab3-95f2-cee0065d2fe4" />

Looks like it's 222ca7c commit

**Comment by CastaChick** [comment]
The current color (`#87fab73a`) has a contrast ratio of nearly 1, which is too low.
To match the colors from versions prior to 2.1.0, I think `#733c1d` would be a good choice.
It has a contrast ratio of over 7, making it sufficiently visible for individuals with colorblind as well.

**Comment by coollugi** [comment]
![CleanShot 2024-12-29 at 20 21 56@2x](https://github.com/user-attachments/assets/db75be18-bbe1-4cd8-8f04-9ad50be0b820)

Also have smilier issue, maybe a bit brighter in dark theme?

**Comment by JohnPiepersSmits** [comment]
> Also have similar issue, maybe a bit brighter in dark theme?

Like coollugi: I see the same thing too, and have reverted back to the 2.0.2 version of Night Owl for the time being.

John

**Comment by latuprez** [comment]
Yeah I'm also seeing the dark gray brackets now and I find it really tough to see and parse. Going to try reverting to an older version

**Comment by sebbean** [comment]
also seeing this ya'll!

hi mom

**Comment by nikunj-26** [comment]
The bracket colors looked super weird in the dark theme! Reverted back to v2.0.2. Imo the color scheme for brackets in v2.0.2 is perfect

**Comment by ATLCode** [comment]
Glad to see I wasn't the only one. With dark theme some parantheses looked grey that was very hard to see.

Reverted to 2.0.2 version like John suggested for now, but obviously this is something that should get fixed when possible.

**Comment by sdras** [comment]
Should be all fixed! Please feel free to reopen if I'm mistaken. Happy new years.
