### ISSUE TITLE
Please document how I can adjust individual colors

### ISSUE THREAD

**Issue by mfour-merickson** [sdras/night-owl-vscode-theme#36]
Here is a quick and dirty issue so you can track the request (as per our conversation on Twitter)

As I have mentioned, the "green" color that is used is closer to "yellow" and causes some confusion for my eyes when executing PHPUnit tests (see screenshot)

![image](https://user-images.githubusercontent.com/31225533/40340063-093f01b0-5d32-11e8-9aaf-51b75cf99ab1.png)

This is how it appears in terminal 

![image](https://user-images.githubusercontent.com/31225533/40340096-2c7f3fdc-5d32-11e8-9f88-a4a1058ecadb.png)

**Comment by mfour-merickson** [comment]
Thank you very much, looking forward to the update.  In the meantime, I will tell my brain (eyes) that magenta is really green when perform PHPUnit testing (I am guessing this would be the same green that would appear for other testing tools such as Jest, Mocha, etc)

**Comment by Dean-Coakley** [comment]
ahhh my git diffs are purple text. Looking forward to fix/docs! 👍

**Comment by sdras** [comment]
I'm at a conference but it will be soon! Thanks for your patience.

**Comment by sdras** [comment]
Hi! I couldn't sleep so I went and tracked this down. I thiiiiiiink it should be better now, can you please check and see if it looks good to you two? Thanks!

**Comment by Dean-Coakley** [comment]
@sdras Sorry to hear that.

Definitely much better. Green instead of purple! I think I might like if green could be a bit brighter but perhaps that would increase eye strain in low light.

Open to other opinions...

**Comment by cthos** [comment]
If you do find yourself needing to change colors in a given theme, here are good instructions:

https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme

The one in question I think is `terminal.ansiGreen`.

**Comment by sdras** [comment]
@cthos that is literally what was in the last commit/release that fixed the problem. I'll adjust it slightly from here to make it brighter, but this is fixed.

**Comment by cthos** [comment]
:+1: - Sorry for the confusion.

**Comment by mikeerickson** [comment]
![image](https://user-images.githubusercontent.com/183153/40496827-8939b94c-5f2f-11e8-855f-062826c18c81.png)
