### ISSUE TITLE
Suggestion: Could you provide a free font alternative?

### ISSUE THREAD

**Issue by ricardofpcorreia** [sdras/night-owl-vscode-theme#38]
Theme looks awesome. But, it would be great if you have an alternative version using a free font.
Congrats!

**Comment by sdras** [comment]
Sure! Fira Mono is one: https://github.com/tonsky/FiraCode. To be clear, this theme doesn't "use" Dank Mono, it's just the font in the screenshots because I knew people would ask. Thanks
