### ISSUE TITLE
Suggestion: Add vertical line to help see block scope

### ISSUE THREAD

**Issue by gerardo-rodriguez** [sdras/night-owl-vscode-theme#39]
Thanks so much for this theme @sdras! I've been enjoying it thus far! 🎉 

One thing I just noticed is that most (if not all) of the other themes have a vertical line to help distinguish block scope. I have never jumped into the theme making world, so have no clue how this is done, but if it's not too much of a bother I'd like to make the suggestion of adding this to your Night Owl theme. Thank you for your consideration! 😄 

![vertical-line](https://user-images.githubusercontent.com/459757/40376672-c1f3cf76-5da3-11e8-98b6-e9bef6f61977.gif)

### Monokai Dimmed

Notice a vertical line to help distinguish block scope.

![screen shot 2018-05-22 at 9 25 17 am](https://user-images.githubusercontent.com/459757/40376187-847973cc-5da2-11e8-830b-41771fcc78f3.png)

### Night Owl

Notice no vertical line.

![screen shot 2018-05-22 at 9 26 24 am](https://user-images.githubusercontent.com/459757/40376163-775f3bae-5da2-11e8-9436-d115624756ef.png)

**Comment by sdras** [comment]
Ah, yep! Thats a bug! Sorry about that, I'll get it fixed!

**Comment by sdras** [comment]
well that's just adorable

**Comment by sdras** [comment]
ok! please update, this should be fixed now!

**Comment by gerardo-rodriguez** [comment]
Thank you @sdras!!! Much appreciated! 😄
