### ISSUE TITLE
Scrollbar color is Indistinguishable from background Color

### ISSUE THREAD

**Issue by cthos** [sdras/night-owl-vscode-theme#4]
On my mac at least, the scrollbar color is the same as the background color so you can't really see where it is.

In the attached screenshot you can just barely see it where it's blocking out the side margin's line right below the blue change mark.

<img width="64" alt="screen shot 2018-05-17 at 3 40 32 pm" src="https://user-images.githubusercontent.com/456545/40207482-8f7f52a8-59e9-11e8-842c-653e283fffaa.png">

**Comment by sdras** [comment]
Good call! Thanks!

**Comment by sdras** [comment]
I just updated this, can you please check it out and let me know if you see it now/ works on your machine :)

**Comment by cthos** [comment]
Yeah! Looks good. 🎉 

Any chance I can make another small suggestion to turn the opacity down a touch so the changed line color indicators can still be seen through it?

**Comment by sdras** [comment]
oh for sure! That's a good idea. 👍

**Comment by cthos** [comment]
I tried this locally, looks pretty okay?

```

**Comment by sdras** [comment]
Oh I didn't see this while I was working- I think I got it fixed though! It's a little brighter than the one you have there. Can you please reload the theme and check it out? Thanks!

**Comment by cthos** [comment]
Yeah, looks good!

**Comment by sdras** [comment]
Great! thanks
