### ISSUE TITLE
Parenthesis occasionally on italics looks "weird?"

### ISSUE THREAD

**Issue by gnapse** [sdras/night-owl-vscode-theme#42]
Not sure if "weird" is the right word, but:

![image](https://user-images.githubusercontent.com/15199/40428860-3fb293ea-5e6f-11e8-9d6c-62b3f80d3f9e.png)

The circled areas should be self-explanatory, but I'll express here in words what they're about:

1. Parenthesis are shown in italics when calling a function, but not when declaring a function.
2. Parenthesis in italics, while the inner braces when passing an object literal to a function call are not.
3. Unlike with braces in the previous point, if you pass an array literal, the square brackets are in italic, which go along better with the wrapping parenthesis also in italics (I realized this last one after I took the screenshot so it's not there).

I'd say either all of these wrapping-kind of pairs of characters should be in italics, or none. I'm referring specifically to `()`, `{}`, `[]`, and leaving string quotes out of the equation. In particular, the fact that parenthesis are put in italics some times and not in all situations, and square brackets are in italic but braces are not, seems odd.

Thoughts?

**Comment by gnapse** [comment]
Ok, sorry, I updated to the latest version and most of the issues, if not all, were gone.

I still do not quite get though what's the rationale for what things go in italics and what things don't. For instance, in an object literal, functions declared with the shorthand notation are not in italic, and object property names are in italic:

```javascript
const obj = {
  thisIsNotInItalic() { ... },

  thisIsInItalic: () => { ... },
  thisTooIsInItalic: true,
}
```

Another thing which is perhaps more odd:

```javascript
this.set('name', name) // Here `set` is in italic
this.setName(name) // Here `setName` is not in italic
this.setName // Here `setName` is in italic, apparently because is not used as function
// In both cases `this` (or whatever comes before the dot) is in italic
```

It looks like there's something special with `something.set` because in any other `something.method` call, the `method` is not in italic **when used as a function call**.

Not saying it's wrong, but wanted to bring attention to that as well.

As for the original issue I was reporting, it's solved in 0.2.1.

**Comment by sdras** [comment]
Excellent, closing this out. I have some settings documented in the readme for turning off the italics if you wish. I have a writeup explaining some of the choices (not every one line by line, because I talk about a lot of other things too, but the general gist.) I may make a no-ital theme too.

**Comment by gnapse** [comment]
Thanks!

BTW, +1 on the no-ital alternative, but I think it's ok to use them in the comments. I did copy the README settings and removed comments so they keep italic.

**Comment by sdras** [comment]
👍

**Comment by gnapse** [comment]
I think I found another apparent inconsistency with the use of italics, but I'll add it here in case it's intentional behavior:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/15199/40892475-ab9f85a0-6765-11e8-83d2-5a3e843d5b98.png">

1. Variable `parsingError` is shown italics when declared in line 59, but then is not in italics when used in line 61. Is that intentional? Seems odd, because I'd expect the same "thing" to appear always the same visually.
2. The same happens with the argument `css`, which is not in italics when declared as argument in line 55, but then it's shown in italics when passed as argument to `parseCSS` in line 60.
3. On the other hand, the argument `htmlElement` is not rendered in italics when passed as argument to `checkHtmlElement` in line 56, but then it's rendered in italics when passed as an argument to `getComputedStyle` in line 57. This is really odd, because I'd expect that if variables are shown in italics or not when passed as arguments, it'd be that way for all variables being passed as arguments.
4. This one may be because content within backtick string interpolations is italics, but it's odd that `this.isNot` is italics in line 71, and not italics in line 63.

**Comment by sdras** [comment]
Hi! I haven't read through this all yet, but can you please open it in another issue? It will help keep things organized. Thanks

**Comment by gnapse** [comment]
Sure, done (#71).

**Comment by sdras** [comment]
Thanks!
