### ISSUE TITLE
Vim Visual Mode blanks out selected text if it's highlighted

### ISSUE THREAD

**Issue by cthos** [sdras/night-owl-vscode-theme#43]
Okay, so here's a weird one for you.

If you open up vim in the integrated terminal, and highlight some text via Vim's visual mode that isn't styled, it'll vanish (I think because it turns the text the same color as the background, not that the highlight is covering it up though I can't be sure).

I made a video to illustrate the problem [https://cthos-backups.nyc3.digitaloceanspaces.com/images/vim_visual_mode.mp4](https://cthos-backups.nyc3.digitaloceanspaces.com/images/vim_visual_mode.mp4)

And here are some screenshots:

Before Visual mode highlighting:
![vim1](https://user-images.githubusercontent.com/456545/40449510-822c65f2-5e8d-11e8-8249-40bde26f3ecf.PNG)

After Highlighting:
![vim2](https://user-images.githubusercontent.com/456545/40449512-82461c0e-5e8d-11e8-8ccf-3274caaea296.PNG)

**Comment by sdras** [comment]
Oh yuck! I'm so sorry! I'll get this fixed as soon as I can, that's a bug on my part.

**Comment by cthos** [comment]
No need to apologize! I'll start learning how VSCode theming actually works so I can give you a PR instead of just opening issues. 😸

**Comment by sdras** [comment]
Hi! I think I might have just fixed it- can you please reload the extension to the latest version and tell me how it is? Thanks!

**Comment by cthos** [comment]
Looks like it's still happening on 0.2.2:

![vim3](https://user-images.githubusercontent.com/456545/40454893-6a440582-5e9f-11e8-8e36-66fa703bb13a.PNG)

**Comment by cthos** [comment]
This is also just on Vim's default colorscheme, changing it to `ron` doesn't have the same issue - the default clears out the normal color so I'm not really sure what's going on there.

**Comment by cthos** [comment]
@sdras - Actually, I don't think this is the theme's fault - It's also happening on the default themes.

I'm really sorry I should have checked that first.

**Comment by cthos** [comment]
For reference I think the problem is that Vim sets the highlight color by default to whatever the background color of the terminal is, and there doesn't appear to be a way to deal with that - I'm going to go check the VS Code repo and see if there's an issue for this already.
