### ISSUE TITLE
Italic || in rust code confusing

### ISSUE THREAD

**Issue by killercup** [sdras/night-owl-vscode-theme#45]
Love your theme! It's finally convinced me to switch back to a dark one.

There is one small annoyance, though. In Rust, you can write an anonymous function with no parameters that returns 42 like this `|| 42`. In expression contexts, `||` is also boolean OR. So, I was quite surprised to see the double-pipe set in italic -- which looks like `//`, the start of a line comment.

The span in question looks like this:

```html
<span class="mtk3 mtki">||</span>
```

Maybe you can either make operators non-italic in Rust or special case this case if possible?

**Comment by sdras** [comment]
Hi, I think I might have fixed this, can you please try to update/reload to the latest version and let me know if it's resolved? Thanks!

**Comment by sdras** [comment]
I'm going to close this out but if you find it's still not taken care of, please feel free to reopen!

**Comment by killercup** [comment]
Thanks, works perfectly!

And sorry for the late response -- I'm in Paris for RustFest since Thursday (and I can now tell people IRL that this theme is awesome)
