### ISSUE TITLE
Text in divs/components have no contrast

### ISSUE THREAD

**Issue by sdras** [sdras/night-owl-vscode-theme#47]
Example here:
https://twitter.com/kentcdodds/status/999779167053856770

**Comment by wistcc** [comment]
Hey @sdras,

Checking the issues I noticed this one and AFAICT is fixed on the latest version.

![image](https://user-images.githubusercontent.com/4671080/40571244-808252f2-6063-11e8-9886-24ca0f3a41d7.png)
 
I wrote the same example Kent did on the `demo/react.js` file. :)

**Comment by sdras** [comment]
Thanks! I just updated this to be consistent with the way that it works in HTML, because that should be the same, while this particular color is now used to call out React components in particular. If you update you should see it. Thanks!
