### ISSUE TITLE
Powerlevel9k colors are washed out in integrated terminal

### ISSUE THREAD

**Issue by cthos** [sdras/night-owl-vscode-theme#5]
Not sure how relevant this would be for other people, but the colors of the Default powerlevel9k settings in zsh appear washed out in the Integrated terminal making them a bit difficult (for me at least) to read.

<img width="1052" alt="screen shot 2018-05-17 at 3 17 49 pm" src="https://user-images.githubusercontent.com/456545/40207631-4f71ac32-59ea-11e8-97da-7fb0f3142155.png">

For comparison, here's the Dracula theme:

<img width="1054" alt="screen shot 2018-05-17 at 3 52 52 pm" src="https://user-images.githubusercontent.com/456545/40207639-611591ba-59ea-11e8-964c-483cf9c46743.png">

**Comment by sdras** [comment]
Totally, I didn't do adequate testing for the terminal, thanks for bringing it up! I'll fix it up for the next release

**Comment by sdras** [comment]
Hey! I think I might have fixed this. Can you please double check? Thanks!

**Comment by cthos** [comment]
Looks a bit better, but the blacks are a bit off. I took a shot at adjusting the ansiBlack colors a bit.

Published Theme:
<img width="491" alt="screen shot 2018-05-17 at 7 50 40 pm" src="https://user-images.githubusercontent.com/456545/40213799-3d92763c-5a0c-11e8-8406-e39e5a4e4f55.png">

Adjustments:
```
"terminal.ansiBlack": "#333333",
"terminal.ansiBrightBlack": "#787878",
```

<img width="1066" alt="screen shot 2018-05-17 at 7 54 36 pm" src="https://user-images.githubusercontent.com/456545/40213811-4deb9c98-5a0c-11e8-816c-290fbfc6ab75.png">

⚠️ I changed the brightBlack value because of that autocomplete plugin using it for its "this is the next set of characters in the auto complete" as illustrated in the screenshot.

I think the blacks are the only things that need changing.

I checked the `pygmalion` theme as well and it looks good.

<img width="630" alt="screen shot 2018-05-17 at 7 57 38 pm" src="https://user-images.githubusercontent.com/456545/40213867-96d950b2-5a0c-11e8-8d43-998aca9013a3.png">

**Comment by sdras** [comment]
Ok I think I got it sorted, please reload and let me know what you think :)

**Comment by cthos** [comment]
Yeah! Looking great now. Thank you!

**Comment by sdras** [comment]
Excellent. Thanks!
