### ISSUE TITLE
feat: improve keyword recognition by making color unique

### ISSUE THREAD

**Issue by alexsasharegan** [sdras/night-owl-vscode-theme#52]
First off, thanks for working hard on bringing a new theme to the community that really feels truly original in the wide sea of theme options!

## Problem

In JavaScript (and possibly other languages), there is a color duplication between keywords and object keys. This reduces the visibility of keywords, since they don't have a unique color by which to identify them.

### Example

<img width="445" alt="screen shot 2018-05-26 at 14 22 38" src="https://user-images.githubusercontent.com/16269252/40580322-b5c9e5f0-60f0-11e8-91f8-363d5e39f41e.png">

The `debugger` statement is not easily discernible among the object keys using the same color.

### Ideas

For reference, here's the default dark theme from code:

<img width="436" alt="screen shot 2018-05-26 at 14 28 02" src="https://user-images.githubusercontent.com/16269252/40580336-06342136-60f1-11e8-9672-0c332edf9c78.png">

It's interesting to note that they use a lighter version of the keyword. Maybe that's an idea to riff off? Take it wherever you want to, but I thought I would at least offer some potential inspiration.

## Side Note

While playing with example code, I noticed that there are keywords that use a different color, like in a `for..of` loop:

<img width="755" alt="screen shot 2018-05-26 at 14 33 56" src="https://user-images.githubusercontent.com/16269252/40580383-e5d66132-60f1-11e8-81f5-f23340f23414.png">

This seems consistent with other themes like the default dark (again):

<img width="789" alt="screen shot 2018-05-26 at 14 33 44" src="https://user-images.githubusercontent.com/16269252/40580384-ea379eee-60f1-11e8-93e5-2561ef2d5bb9.png">

What seems different is how the alt color is used. You're certainly welcome to approach this however you see fit, but it appears that there are subclasses of keywords. My first concern with a theme is about instant control flow recognition, so I like when themes are consistent in how they group the coloration of things. On a sub-side note, you can also see that class types have some special coloration here.

**Comment by sdras** [comment]
Thanks for reporting this! I definitely see what you mean about the keyword, and I will work on that for the next release. For the other side notes, there are very intentional reasons why I have highlighted and contrasted certain colors sparingly. Eventually things become rainbow noise and I've worked very hard to keep the contrasts to a minimum but meaningful, especially in colorblind testing, and some things are the colors that they are in different references depending on what's surrounding them. I don't think it's productive to compare/contrast with other themes, because there are many parts of decisions that lead up a whole. If you're happier with the dark theme, that sounds like a better theme for you.

**Comment by alexsasharegan** [comment]
The dark theme refs were just a common reference to compare some things and come up with ideas. It's really cool to hear why you've taken a different approach on those other points. I totally respect that.

**Comment by sdras** [comment]
OK! This should be fixed now, please upgrade to the latest version. I did a few refinements as well, especially for things like case/switch/break, and ruby. Please feel free to reopen if anything looks weird.

**Comment by alexsasharegan** [comment]
I’ll update and check it out today! I'm sure it's all worked out. Thanks for this!

**Comment by alexsasharegan** [comment]
I see that some keywords have changed, but are the object keys supposed to still be the purple color?

![image](https://user-images.githubusercontent.com/16269252/40590081-ae5f09fe-61ad-11e8-94f8-e5c76ad87fea.png)

**Comment by alexsasharegan** [comment]
I think I've found the scope to play with this for JS.

```json
{
  "name": "Storage",
  "scope": [
    "source.js meta.objectliteral.js meta.object.member.js meta.object-literal.key.js"
  ],
  "settings": {
    "foreground": "#e0c2f2",
    "fontStyle": "italic"
  }
}
```
