### ISSUE TITLE
Color Issues inside PHP classes 

### ISSUE THREAD

**Issue by stefanrempe** [sdras/night-owl-vscode-theme#53]
I noticed some color issues with PHP classes where accessing a property has the same color as "$this->". 

![image](https://user-images.githubusercontent.com/14946911/40590200-07155aec-61fb-11e8-874c-9ff6784ea72e.png)

**Comment by sdras** [comment]
Dang, sorry about that. I'll get it fixed in the next release.

**Comment by stefanrempe** [comment]
Thanks for this quick response and beautiful theme.
