### ISSUE TITLE
New Logo For night-owl-vscode-theme

### ISSUE THREAD

**Issue by iqbalhood** [sdras/night-owl-vscode-theme#55]
Hi @sdras, I love the Night Owl Vscode theme you made. Let me create a logo for this project. Thanks :)

**Comment by sdras** [comment]
Hi! I kinda like the logo, but if you make one I like better, I will use it. I'm not sure I could say I would take it until I see it :)

**Comment by iqbalhood** [comment]
Okay Never Mind, Let Me Do it for you :)  👍

**Comment by iqbalhood** [comment]
Hello, @sdras 
These are my logo proposal for your project. If there any revision, please just tell it.

![owl](https://user-images.githubusercontent.com/1563756/40784832-f286e44c-6510-11e8-99e4-e2105b075ced.jpeg)

![owl2](https://user-images.githubusercontent.com/1563756/40784834-f2cf4ebc-6510-11e8-87ec-9704080ae25a.jpeg)

**Comment by sdras** [comment]
Thank you Iqbal, these are really nice! But I still really like my original logo. I'm going to keep it as it is. Best wishes.
