### ISSUE TITLE
Mention ported versions?

### ISSUE THREAD

**Issue by nickcernis** [sdras/night-owl-vscode-theme#56]
Just to let you know that Night Owl's already been ported to iTerm 2 and Hyper:

- Hyper: https://github.com/pbomb/hyper-night-owl
- iTerm2: https://github.com/nickcernis/iterm2-night-owl

Could be mentioned in the readme or wiki, perhaps? Or not! That is fine too. :-)

**Comment by sdras** [comment]
Yep! Great idea. Will do.

**Comment by sdras** [comment]
This one too: https://github.com/jsit/night-owl-iterm2-theme

**Comment by nickcernis** [comment]
Another: https://github.com/florianeckerstorfer/night-owl-itermcolors

**Comment by MurZimminy** [comment]
Here's one for Atom: https://discuss.atom.io/t/vs-code-night-owl-by-sarah-drasner-accessible-theme-ported/55446

**Comment by xdrop** [comment]
Just published one for Jetbrains IDEs 😃 

https://github.com/xdrop/night-owl-jetbrains

**Comment by sdras** [comment]
done!
