### ISSUE TITLE
light version

### ISSUE THREAD

**Issue by tbsvttr** [sdras/night-owl-vscode-theme#59]
I know it sounds a bit strange, but I would love a light version of this theme. I often find myself programming in bright environments where I simply can not see dark themes very good. However, this theme is so meticulously crafted that I would love a version which I could still use in such an environment.

At the moment I use [Monokai Light](https://github.com/anoff/vscode-monokai-light) or [Gitbub Clean White](https://github.com/saviorisdead/vscode-github-clean-white-theme) for this.

**Comment by sdras** [comment]
I actually am planning on doing this, I'm just not sure when I'll have the time. Probably in the next month or so. Thanks!

**Comment by chibicode** [comment]
Also waiting for the light theme :) I also like bluloco-light: 
https://medium.com/@chibicode/the-best-visual-studio-code-dark-and-light-themes-july-2018-edition-a9c2cc9548da

**Comment by tbsvttr** [comment]
@chibicode bluloco-light is nice, but it has the problem that it does not support italics.

**Comment by uloco** [comment]
I am planning to add support for italics. Would you mind me telling, which words you want to have in italics? keywords only? https://github.com/uloco/theme-bluloco-light

**Comment by sdras** [comment]
Light Owl theme now introduced! Let me know what you think. :)

**Comment by frebro** [comment]
You named it Light Owl 🙌😂

**Comment by chibicode** [comment]
@sdras it looks great! I added it here: https://medium.com/@chibicode/the-best-visual-studio-code-dark-and-light-themes-july-2018-edition-a9c2cc9548da

**Comment by dagolinuxoid** [comment]
@sdras, even though dark themes at firs glance looks cooler I prefer to spend time coding in light ones. Thankfully I've discovered Night Owl Light (no italics) theme at CodeSandbox (yep, they included it in their list of themes). At the time I didn't even know who is the author, but since I know it now I decided to drop the comment as an act of appreciation. Good job =)
