### ISSUE TITLE
highlight matched strings

### ISSUE THREAD

**Issue by mobayen** [sdras/night-owl-vscode-theme#6]
Matched words don't get highlighted anymore.
in the image, all 'test's supposed to get a slight highlight.

![matched strings](https://user-images.githubusercontent.com/29548601/40207945-9d26566e-59fc-11e8-9aa5-8b589d93aa6b.png)

**Comment by sdras** [comment]
Ah interesting, I'll check that out. Thanks.

**Comment by sdras** [comment]
hey hey, do you know of a theme that this works on? what was your previous theme? I'm having a hard time tracking down exactly how to target it.

Looks like matched words are working in most of the other files that I'm testing on so could you please let me know what language you're referring to here? that would help! thanks 
<img width="378" alt="screen shot 2018-05-17 at 7 24 17 pm" src="https://user-images.githubusercontent.com/2281088/40211450-18c8835e-5a08-11e8-96d3-2b210459ac10.png">

**Comment by remarks** [comment]
I'm getting this as well. Tested with HTML, Vue, and JavaScript languages. Works in the default themes for me.

**Comment by cthos** [comment]
Can confirm that this _works_ in Typescript for me:

<img width="353" alt="screen shot 2018-05-17 at 11 53 18 pm" src="https://user-images.githubusercontent.com/456545/40220282-81d7a18e-5a2d-11e8-924e-24b6e2486666.png">

But does _not_ work in a text file:

<img width="217" alt="screen shot 2018-05-17 at 11 53 51 pm" src="https://user-images.githubusercontent.com/456545/40220315-9d0aad2a-5a2d-11e8-89dc-212bed6fa731.png">

The same text file _does_ work in the [Dracula Theme](https://github.com/dracula/visual-studio-code)

<img width="198" alt="screen shot 2018-05-17 at 11 54 08 pm" src="https://user-images.githubusercontent.com/456545/40220344-b23871c8-5a2d-11e8-91bf-d9e041ea900f.png">

I poked around in their source but I don't see anything obvious in there. 🤔

**Comment by sdras** [comment]
ya'll are awesome, thanks for being on the case! I've set aside some time to work on this today after work. Thanks!

**Comment by diarcastro** [comment]
I like this conbination:
`"editor.selectionHighlightBackground": "#ffffff10",`
`"editor.selectionHighlightBorder": "#ddd"`

![screen shot 2018-05-18 at 3 25 11 pm](https://user-images.githubusercontent.com/2319600/40256332-b4a66b7c-5aaf-11e8-94d5-a30d72503398.png)

It's from OneDark-Pro from Material Theme.

Thanks for your time an this great theme!

**Comment by sdras** [comment]
This should now be fixed! I 'm more of a fan of the background highlight than the border, so I went in that direction. Please feel free to reopen if anything seems amiss. Thanks for the feedback everyone!
