### ISSUE TITLE
Increase contrast for line number foreground

### ISSUE THREAD

**Issue by davidrf** [sdras/night-owl-vscode-theme#60]
Hello! Thank you for such an amazing theme 🌟 

Would you consider increasing the color contrast for the inactive line number? The numbers are a bit hard to see against the background. For example, the numbers 10 and 12 are a little hard to see in the following image:

<img width="57" alt="screen shot 2018-05-29 at 5 51 37 pm" src="https://user-images.githubusercontent.com/9678182/40687570-1d7031c6-6369-11e8-8e3d-c7e5ca6feb80.png">

This isn't a problem when you're coding by yourself. However, I've found that my coworkers and I have a hard time finding line numbers when we're looking at the same screen and we refer to line numbers (i.e. "check out line X").

Thank you for taking the time to read this issue and considering it! Furthermore, I believe the following are the configuration settings that might need to be changed in order to fix this issue if it's accepted: `editorLineNumber.foreground` and `editorLineNumber.activeForeground`.

**Comment by sdras** [comment]
Yeah that sounds good to me :) I'll get it updated in the next release and let you know when it's done. Thanks!
