### ISSUE TITLE
support for PowerShell

### ISSUE THREAD

**Issue by pedropablo** [sdras/night-owl-vscode-theme#63]
First thing: Thank you very much, really nice theme. I used to switch themes depending on the project type. Now I have a couple weeks without switching, they just look great on Night Owl 👍 

I also use VS Code for almost every text editing, and I do a lot of Powershell. And PS scripts looks... kinda funny. 

![image](https://user-images.githubusercontent.com/5614764/40693021-cb04d100-637a-11e8-8d79-ee0c504e6153.png)

Hope you find some time to check it out. Thanks again for your effort!

**Comment by sdras** [comment]
Yeahhh that's really fugly. Would you mind please PR-ing the demo folder with an example file? That would really help me out to get this taken care of, as it's not my typical workflow. Thanks!

**Comment by pedropablo** [comment]
Sure Sarah! I'll get that done first thing morning!

**Comment by sdras** [comment]
This is fixed! Please let me know if there's anything that needs work. Thanks!
