### ISSUE TITLE
Make a carbon theme

### ISSUE THREAD

**Issue by sdras** [sdras/night-owl-vscode-theme#64]
Not high priority, details here:

https://twitter.com/fixitup2/status/1001672452588498944

**Comment by wistcc** [comment]
Some things to take into account before doing this:
- We will need to create a `.css` file which is different from what we already have.
- If we update something here (a color or style) we will need to update it there as well.

I can take a look.

**Comment by wistcc** [comment]
After taking a look, I created this PR https://github.com/dawnlabs/carbon/pull/379 in Carbon's repository.

I hope you like it.

**Comment by sdras** [comment]
Thanks to @wistcc for creating this!
