### ISSUE TITLE
Support for "Git Commit Message" language mode

### ISSUE THREAD

**Issue by erikthedeveloper** [sdras/night-owl-vscode-theme#66]
Hi, I've recently been giving this theme a try (loving it BTW! Thank you 😃). I use VS Code as my git editor and just discovered that Night Owl seems to not support the commit/diff syntax as displayed when committing via `git commit -v`. 

I suspect this is related to the theme itself since I can change to a number of other themes included w/ VS Code and have this syntax highlighting supported.

**Night Owl (no diff highlighting)**

![image](https://user-images.githubusercontent.com/1240178/40747748-79e99962-641b-11e8-92e7-c884b773d211.png)

**Dark (Visual Studio) (diff highlighting)**

![image](https://user-images.githubusercontent.com/1240178/40747806-a74cee90-641b-11e8-8a77-da85969af35b.png)

**Comment by sdras** [comment]
closed thanks to @wistcc!! 🎉
