### ISSUE TITLE
Using line breaks when defining arrow function params causes unexpected syntax highlight behavior

### ISSUE THREAD

**Issue by madisonbullard** [sdras/night-owl-vscode-theme#69]
```
const funcOneLine = (param1, param2) => {}
```
highlights correctly ('funcOneLIne' is blue).

```
const funcLineBreaks = (
  param1,
  param2,
) => {}
```
highlights incorrectly ('funcLineBreaks' is white).

Thanks for a lovely theme. Excellent work.

EDIT: now realizing this may be an issue with `dzannotti.vscode-babel-coloring` instead... Let me know if so

**Comment by sdras** [comment]
Thanks for the issue! I'll take a look and get back to you soon.

**Comment by sdras** [comment]
Hi! Yeah, I can't duplicate this, I think what you're seeing is due to a conflict with another extension. Feel free to reopen if not
