### ISSUE TITLE
Edit filename in Explorer bottom border cut off

### ISSUE THREAD

**Issue by jrsquared** [sdras/night-owl-vscode-theme#72]
When editing a file name in the explorer, the bottom border is cut off.
<img width="487" alt="screen shot 2018-06-04 at 8 01 55 pm" src="https://user-images.githubusercontent.com/56971/40952889-28206ffa-6832-11e8-9224-01b546cf7a10.png">

**Comment by sdras** [comment]
Hm, this might be one of those things that's not the theme, but that you need to file with VS Code itself, but I'll double-check my assumption here and get back to you. Thanks!

**Comment by sdras** [comment]
I looked into this and I can't actually reproduce. Can you please test on other themes and see if you see the same thing? That would allow us to know if it's a problem with the theme or VS code.

**Comment by jrsquared** [comment]
Ah, I forgot that I keep my VS Code zoomed out one level, that's the only time I can reproduce it.
Other themes only have a border on the left side at this zoom level though.
Regardless, not a huge deal...

**Comment by sdras** [comment]
I thought it might be something like that. Yeah, it's not something the theme can change anyways but if it really bothers you, you can file an issue with VS Code, they do a lot of work to fix stuff up :)
