### ISSUE TITLE
import style in .tsx

### ISSUE THREAD

**Issue by cdock1029** [sdras/night-owl-vscode-theme#78]
**version**: 0.3.2

This issue: 
https://github.com/sdras/night-owl-vscode-theme/issues/58

still applies to `.tsx` files

<img width="279" alt="screen shot 2018-06-07 at 1 21 43 pm" src="https://user-images.githubusercontent.com/802586/41115530-cc65ef34-6a55-11e8-92be-30158e1f97bc.png">

**Comment by alpcanaydin** [comment]
<img width="425" alt="screen shot 2018-06-07 at 23 06 59" src="https://user-images.githubusercontent.com/1801024/41123499-81dc6e96-6aa7-11e8-9520-b3b5a4580bc6.png">

Also in javascript files too.
