### ISSUE TITLE
Make "in code" cursor more visible

### ISSUE THREAD

**Issue by mschipperheyn** [sdras/night-owl-vscode-theme#79]
Hi, persuant my tweet, a request to make the cursor more visible when it is "inside code". It's very hard to see. Outside of code, against black it's easy, but inside...
<img width="290" alt="screen shot 2018-06-09 at 09 57 13" src="https://user-images.githubusercontent.com/384959/41191824-8d2a0b62-6bcb-11e8-9128-7ac30d317736.png">

**Comment by sdras** [comment]
That's good feedback, thanks! I'll take a look.
