### ISSUE TITLE
JSX component, this vs member coloring

### ISSUE THREAD

**Issue by mschipperheyn** [sdras/night-owl-vscode-theme#80]
I would like to suggest some more color variations here:
- this should be a different color than a member
- JSX component name should be a different color than a member

<img width="734" alt="screen shot 2018-06-09 at 09 59 05" src="https://user-images.githubusercontent.com/384959/41191849-e989f1ba-6bcb-11e8-9c4f-10d3374ad151.png">

**Comment by sdras** [comment]
Hi! Thanks for visiting. This was actually fixed about 10 version back, please upgrade.

**Comment by mschipperheyn** [comment]
Apparently not. I'm on version 0.3.2 (apparently). Same screenshot.
