### ISSUE TITLE
React syntax coloring not the same as screenshot.

### ISSUE THREAD

**Issue by rosswaycaster** [sdras/night-owl-vscode-theme#83]
Hello! First off, great theme! I'm having trouble matching my React syntax color to the screenshot (which I really love). What extension/language do I need to use to match it? I'll attach what my code looks like vs the themes screenshot for reference. I know I'm being nit-picky 😅. Thanks for the help!

Notice:
1. "class" on line 6 is not italicized
2. The imported component "Button" on line 17/19 isn't the same as the other tags
3. "export default" on line 25 is not purple or italicized

**Mine:** (Also using Dank Mono font)
![screen shot 2018-06-10 at 7 49 57 pm](https://user-images.githubusercontent.com/1231836/41208329-ea96845c-6ce7-11e8-8a20-3665c0215c58.png)

**How it is supposed to look:**
![screen shot 2018-06-10 at 7 50 44 pm](https://user-images.githubusercontent.com/1231836/41208336-f71ec824-6ce7-11e8-907a-0f2dc5efe01d.png)

**Comment by rosswaycaster** [comment]
These are the extensions I currently have installed

![extensions](https://user-images.githubusercontent.com/1231836/41208547-63d12f50-6cea-11e8-8783-a2f7580720c8.png)

**Comment by sdras** [comment]
These are all things that have been asked for and addressed in issues and PRs and releases since it first launched. I can update the screenshot, but full disclosure, it's not a super high priority at the moment because there are only small differences.

If you'd like to submit a PR to fix it though, I'd be more than happy to take it :)

**Comment by rosswaycaster** [comment]
Well I feel silly now 😄 I'd be happy to update the screenshots! Thanks again for the theme!
