### ISSUE TITLE
Add syntax highlighting for flow comment syntax

### ISSUE THREAD

**Issue by Noviny** [sdras/night-owl-vscode-theme#87]
NB: I had some poking around at scoping in vs-code theme options, and it looks like the internals of comments don't have type information:

![image](https://user-images.githubusercontent.com/15622106/41272268-ce9ae722-6e57-11e8-9283-e7a69841d2dc.png)

which implies that targeting parts of a comment isn't possible. If that's true, this should just be closed. Otherwise if there is a scope that can work to target these, happy to look into implementing this.

**Describe the solution you'd like**
In flow, you can use a comment syntax to add types:

```
/*::
type a = number;
*/
```

or:

```
const b/*: number */ = 5
```

It would be nice if the comments that contained type information had syntax highlighting instead of being in comment-grey as they include information. An example of this kind of highlighting:

![image](https://user-images.githubusercontent.com/15622106/41272121-3bc367f8-6e57-11e8-8c19-f9d9b47946f0.png)

**Comment by sdras** [comment]
You're correct- I can't target this directly. If you can either
1. point out a theme that targets this correctly or
2. file an issue with VS code so that I can target it
I will reopen this issue and work on it :)

Thanks for visiting, sorry about the lack of support here.

**Comment by Noviny** [comment]
Thanks for the swift reply!

It looks like since the types for js are derived from ts, this means this syntax would need to be added into typescript itself, which has its own ongoing conversation around comment types.

Sorry for raising this non-useful request. Thanks for the awesome theme. :)
