### ISSUE TITLE
Lighter color for Active Indent Guide

### ISSUE THREAD

**Issue by ptpaterson** [sdras/night-owl-vscode-theme#88]
---
name: Lighter color for Active Indent Guide
---

**Describe the solution you'd like**
Assign a lighter color to `editorIndentGuide.activeBackground`

**Is your feature request related to a problem? Please describe.**
I have been using this theme for a while, but didn't even notice that the "active" indent guide had a different color.  When I learned that there was a setting for this, I immediately changed it to something lighter.  The theme only needs to be a little bit lighter for it to be noticeable.  We can always change it ourselves if we want it super obvious!

**Comment by sdras** [comment]
Ah you know, my bracket pair colorizer extension was overriding this so I didn't see it. I'll disable it and work on it, thanks!

**Comment by wistcc** [comment]
Yeah, I also use Bracket Pair Colorizer and didn't notice before. I'm fixing it here #89 though.

**Comment by sdras** [comment]
You have a really accurate name, Winner. You're definitely a winner. I'll go review.

**Comment by wistcc** [comment]
Hahahah. Thanks!
