### ISSUE TITLE
Unreadable Inactive Tabs in Unfocused Split Editor 

### ISSUE THREAD

**Issue by anggras** [sdras/night-owl-vscode-theme#9]
![unreadable tab](https://user-images.githubusercontent.com/3928555/40213449-1129a936-5a88-11e8-9594-9d52c5a2bd40.jpg)

**Comment by sdras** [comment]
Oh weird! Thanks for reporting this, I'll take a look

**Comment by anggras** [comment]
`"tab.unfocusedInactiveForeground": "#5f7e97"`

Should do the trick :wink:

**Comment by sdras** [comment]
Fixed!
