### ISSUE TITLE
Contrast between the same words highlighted and selected

### ISSUE THREAD

**Issue by kierzniak** [sdras/night-owl-vscode-theme#90]
Hi,
thank you for your work on this great theme.  👍 

I think that contrast between the same word highlighted and the same word selected is to small. Take a look at my screenshot first three `top` words are selected with cmd + d the other three are just highlighted. It is often confusing to me.

![screenshot](https://user-images.githubusercontent.com/590020/41460869-4ddb246a-708e-11e8-99ea-181d6be83336.png)

**Comment by sdras** [comment]
Hi! Thank you for reporting. At first I didn't see what you mean but taking a look, you're absolutely right. I'll get this fixed soon.

**Comment by chibicode** [comment]
You can modify it through `"workbench.colorCustomizations"`. Originally, it had `"editor.selectionBackground": "#1d3b53"`, which was `HSB(207, 65, 35)`. I've increased brightness to `HSB(207, 65, 60)`, which made it `#366C99`.

```json
{
	"workbench.colorCustomizations": {
	    "[Night Owl]": {
            "editor.selectionBackground": "#366C99",
        },
    }
}
```

**Comment by chibicode** [comment]
@sdras Also, I've noticed that, if you **search for a word**, and then select the matching word, then it's hard to tell that the word is selected. In the example below, I've searched for "goodbye" and then tried to select "goodbye" by double clicking the word:

<img width="516" alt="screen shot 2018-06-18 at 6 43 32 pm" src="https://user-images.githubusercontent.com/992008/41571336-952050f2-7327-11e8-9405-430d0cd480cf.png">

**Comment by bsvipas** [comment]
This is hard to fix because VS Code works that way. You need carefully match up colors and make them transparent. As an example, you can take Dark+ theme which is default theme, but to search for colors you need to go through VS Code source since it's built-in theme.

https://github.com/Microsoft/vscode/issues/34105#issuecomment-328775848

**Comment by isaacplmann** [comment]
@chibicode Thank you!  This has been bugging me for a while - but not enough for me to figure out how to fix it.

**Comment by isaacplmann** [comment]
So I did end up having to make a few more tweaks to make it really work the way I wanted.

You can make colors transparent by adding another two hex digits on the end of the color, like this `#RRGGBBAA`.  `editor.findMatchHighlightBackground` was being applied at the same time as `editor.selectionBackground` for me, so I needed to make `editor.findMatchHighlightBackground` have some transparency.

```
    "workbench.colorCustomizations": {
        "[Night Owl]": {
            "editor.selectionBackground": "#366c99",
            "editor.wordHighlightBackground": "#366c9933"
        },
    }
```

End result:
1. I have selected `pu` on the bottom.
2. My cursor is on `.push` so all the matching `.push` words have a transparent layer added.
3. All the other `pu` characters have another transparent layer added.

<img width="464" alt="screen shot 2018-07-20 at 11 30 07 am" src="https://user-images.githubusercontent.com/861504/43011072-5f93c912-8c10-11e8-8d2e-1346f67d719f.png">

Theming is hard.  @sdras thanks for sharing this theme with everyone!

**Comment by chibicode** [comment]
I've copy-pasted from another excellent dark theme [Bluloco Dark](https://github.com/uloco/theme-bluloco-dark):

```json
{
  "workbench.colorCustomizations": {
    "[Night Owl]": {
      "editor.selectionBackground": "#3d577777",
      "editor.selectionHighlightBackground": "#333740",
      "editor.wordHighlightBackground": "#3b4b5f",
      "editor.wordHighlightStrongBackground": "#642856",
      "editor.findMatchBorder": "#ffcc00",
      "editor.findMatchBackground": "#177849b2"
    }
  }
}
```

**Comment by sdras** [comment]
This is all awesome feedback! I'm slammed for the next few weeks but I'll try to get this in when I can (though probably in slightly lower contrast than the dakara theme).

I'd also take a pull request for it if you want it faster. Cheers everyone!

**Comment by dakaraphi** [comment]
@chibicode I found it very hard to make a theme that both looked good and had enough contrast in the selections that made them easily recognizable.

Unfortunately, VSCode doesn't have the ability to inverse the text color or specifically adjust the text color in conjunction with selections.  Also, if you add alpha to the selections they will mix in ways that might not be desirable.  When the selections stack, the result is often text that is barely readable.  So that is why I eventually removed alpha from most selections.

**Comment by chibicode** [comment]
@dakaraphi thanks for the info! I agree that this customization feature is causing a lot of headaches. I've forwarded your comment here: https://github.com/Microsoft/vscode/issues/34105#issuecomment-408679611

@sdras thanks, no pressure!

**Comment by kierzniak** [comment]
I have been using @chibicode suggestions for some time and it is working for me really good. I see some inconsistency between languages but this is probably problem of vscode itself not the theme. One think I'm not sure about are colors. Do they fit Night Owl?

**HTML: cursor before div**
<img width="644" alt="html-cursor_before_div" src="https://user-images.githubusercontent.com/590020/45542599-aad7ed80-b812-11e8-8dec-73649b9c541f.png">

**HTML: cursor in div**
<img width="644" alt="html-cursor_in_div" src="https://user-images.githubusercontent.com/590020/45542615-b5928280-b812-11e8-9af8-9cbd5cb5ab9b.png">

**HTML: search for div**
<img width="644" alt="html-search_for_div" src="https://user-images.githubusercontent.com/590020/45542623-ba573680-b812-11e8-8023-5af1ba2fb757.png">

**HTML: select div**
<img width="644" alt="html-select_div" src="https://user-images.githubusercontent.com/590020/45542632-c04d1780-b812-11e8-9943-4bfb8596324a.png">

**HTML: select all divs**
<img width="644" alt="html-select_all_divs" src="https://user-images.githubusercontent.com/590020/45542637-c4793500-b812-11e8-8dcf-9efcd0f1d677.png">


**CSS: cursor before image**
<img width="644" alt="css-cursor_before_image" src="https://user-images.githubusercontent.com/590020/45542648-cba04300-b812-11e8-9db4-120b9183f427.png">

**CSS: cursor in image**
<img width="644" alt="css-cursor_in_image" src="https://user-images.githubusercontent.com/590020/45542654-cf33ca00-b812-11e8-9164-6b3b2348bb9a.png">

**CSS: search for image**
<img width="644" alt="css-search_for_image" src="https://user-images.githubusercontent.com/590020/45542657-d22eba80-b812-11e8-898f-f022661904ad.png">

**CSS: select image**
<img width="644" alt="css-select_image" src="https://user-images.githubusercontent.com/590020/45542661-d6f36e80-b812-11e8-8446-2ce749fdb6af.png">

**CSS: select all images**
<img width="644" alt="css-select_all_images" src="https://user-images.githubusercontent.com/590020/45542669-dc50b900-b812-11e8-8d49-24511d2fc4a8.png">


**JS: cursor before image**
<img width="644" alt="js-cursor_before_image" src="https://user-images.githubusercontent.com/590020/45542679-e1156d00-b812-11e8-8057-fe9eeebe9482.png">

**JS: cursor in image**
<img width="644" alt="js-cursor_in_image" src="https://user-images.githubusercontent.com/590020/45542688-e4a8f400-b812-11e8-8407-48655ea312f6.png">

**JS: search for image**
<img width="644" alt="js-search_for_image" src="https://user-images.githubusercontent.com/590020/45542694-e83c7b00-b812-11e8-9dba-850efb6a5845.png">

**JS: select image**
<img width="644" alt="js-select_image" src="https://user-images.githubusercontent.com/590020/45542706-ee325c00-b812-11e8-8d1e-098e69cbe557.png">

**JS: select all images**
<img width="644" alt="js-select_all_images" src="https://user-images.githubusercontent.com/590020/45542713-f4c0d380-b812-11e8-8fd2-dd2948a04a41.png">

**PHP: cursor before image**
<img width="644" alt="php-cursor_before_image" src="https://user-images.githubusercontent.com/590020/45542721-fb4f4b00-b812-11e8-90d0-0d60c67162d8.png">

**PHP: cursor in image**
<img width="644" alt="php-cursor_in_image" src="https://user-images.githubusercontent.com/590020/45542734-fee2d200-b812-11e8-8b4c-5f2e54d87735.png">

**PHP: search for image**
<img width="644" alt="php-search_for_image" src="https://user-images.githubusercontent.com/590020/45542744-04401c80-b813-11e8-927a-149d1ac1c581.png">

**PHP: select image**
<img width="644" alt="php-select_image" src="https://user-images.githubusercontent.com/590020/45542751-086c3a00-b813-11e8-92a4-e5dfb9485758.png">

**PHP: select all images**
<img width="644" alt="php-select_all_images" src="https://user-images.githubusercontent.com/590020/45542754-0d30ee00-b813-11e8-99c3-7bde9df8a75f.png">

**Comment by sdras** [comment]
This should be fixed! Please let me know if it still gives you troubles. Thanks.
