### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by chrisdavidstory** [sdras/night-owl-vscode-theme#91]
**Describe the solution you'd like**
React components written in TypeScript should render (e.g. colors and italics) similarly to those written in JS.

**Is your feature request related to a problem? Please describe.**
In some projects, I'm working with React in TypeScript and others in JavaScript. The rendering being different throws me off. Screenshots provided below.

`*.jsx files`
![reactinjs](https://user-images.githubusercontent.com/11340122/41493994-66e04e5c-70db-11e8-9fbc-73d89fb9a110.png)

`*.tsx files`
![reactints](https://user-images.githubusercontent.com/11340122/41493995-6b60d924-70db-11e8-90de-3b5349608694.png)

**Comment by sdras** [comment]
Oh interesting, yeah that's definitely a bug on my part, thanks! I'll get to it soon.

**Comment by palashmon** [comment]
Hi @sdras, I can look into this bug if that is fine with you?

Also, @chrisdavidstory could you please tell what software or online site did you use to get those rounded border images with the box-shadow effect? I really like it.

Regards!

**Comment by chrisdavidstory** [comment]
@palashmon Those screenshots were generated with the [PolaCode](https://github.com/octref/polacode) plugin for VSCode.

**Comment by palashmon** [comment]
Awesome. This is a very useful extension. I will install it now.

Thanks for letting me know about it :+1:
