### ISSUE TITLE
Cursor is very unreadable when positioned on a bracket

### ISSUE THREAD

**Issue by Kurtz1993** [sdras/night-owl-vscode-theme#93]
With Bracket Pair Colorizer turned on:
![image](https://user-images.githubusercontent.com/5412470/41545492-e8e899f2-72e0-11e8-9876-42938b65fe7e.png)

With Bracket Pair Colorizer turned off:
![image](https://user-images.githubusercontent.com/5412470/41545609-2f773518-72e1-11e8-8675-15bdaf4efc27.png)

![image](https://user-images.githubusercontent.com/5412470/41545625-38929b88-72e1-11e8-82bf-2c6d2a7a7baa.png)

![image](https://user-images.githubusercontent.com/5412470/41545631-3d3ada9c-72e1-11e8-8206-c89f8235d793.png)
![image](https://user-images.githubusercontent.com/5412470/41545645-4370f6d0-72e1-11e8-8c84-401fb79bd4c5.png)

![image](https://user-images.githubusercontent.com/5412470/41545657-4af777d0-72e1-11e8-9e30-765d4852ffa3.png)

While working with a React project, I found that it's very difficult to see the cursor when I'm on a bracker, or a parenthesis, etc.

Seems that the colour of the cursor gets merged with the one of the little highlight that the bracket gets.

**Comment by sdras** [comment]
We actually have a fix for that in the cooker! I'll release sometime in the next day or so, and let you know so you can check if it fixed the issue for you. Thanks!

**Comment by sdras** [comment]
This should be fixed! Please reload. Feel free to reopen if your issue isn't resolved.

**Comment by Kurtz1993** [comment]
Seems to be a lot better now :smile: Thanks @sdras
