### ISSUE TITLE
TypeScript React (TSX) coloring

### ISSUE THREAD

**Issue by bsvipas** [sdras/night-owl-vscode-theme#94]
JavaScript React (JSX)
![image](https://user-images.githubusercontent.com/30043375/41553771-72d7d2f4-733b-11e8-8ed3-2ddb838e3408.png)

TypeScript React (TSX)
![image](https://user-images.githubusercontent.com/30043375/41553861-b81699f4-733b-11e8-9ba4-3dbdbb4f385c.png)

Code:

```
import * as React from 'react';
import * as ReactDOM from 'react-dom';

type State = {
  count: number;
};

export default class App extends React.Component {
  private interval: number;
  state: State = { count: 0 };
  
  componentDidMount() {
    this.interval = window.setInterval(() => {
      this.setState((prevState: State): State => ({ count: prevState.count + 1 }));
    });
  }

  componentWillUnmount() {
    window.clearInterval(this.interval);
  }

  render() {
    return <>Hello, current count is: {this.state.count}</>;
  }
}
```

**As you can see TSX coloring is bad.**

**Comment by wistcc** [comment]
I just noticed that this PR https://github.com/sdras/night-owl-vscode-theme/pull/96 also fixes this issue.

This is how it looks now:
![image](https://user-images.githubusercontent.com/4671080/41568689-1b01007e-7335-11e8-8367-71958073d366.png)

@sdras Your call to close it.

**Comment by sdras** [comment]
Wonderful! Thanks Winner.
