### ISSUE TITLE
Restore default status bar colors 

### ISSUE THREAD

**Issue by mikeerickson** [sdras/night-owl-vscode-theme#97]
**Describe the solution you'd like**
I am loving the Night Owl theme, great work!  I have one item that I am looking to change, but not sure exactly where i need to go to do it.

Using most default themes, the bottom status bar is blue (in Code, dont recall what it is when using Insiders release, maybe green), but when Night Owl is active, it takes on the default background color.   Is there a setting where this can be changed (restored to default)

**Comment by mikeerickson** [comment]
@wistcc awesome, thx for that 👍😊

**Comment by wistcc** [comment]
@sdras good to close!

**Comment by mikeerickson** [comment]
I have applied the above settings, but the one for setting background color does not work (the foreground one works fine)

**Comment by mikeerickson** [comment]
![image](https://user-images.githubusercontent.com/183153/41811297-a6fb6d1e-76c1-11e8-9771-4f77aa03b396.png)

**Comment by mikeerickson** [comment]
Arrgh, stupid me, I just needed to reload. My apologies
