### ISSUE TITLE
Colors after 1.25

### ISSUE THREAD

**Issue by ghost** [sdras/night-owl-vscode-theme#98]
https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_25.md

**Added:**
`editorGroup.emptyBackground`: Background color of an empty editor group.
`editorGroup.focusedEmptyBorder`: Border color of an empty editor group that is focused.

**Deprecated:**
`editorGroup.background`: no longer supported with the introduction of the grid editor layout feature.

**Comment by palashmon** [comment]
Thanks for letting us know about it. We will try to fix it in next release.

Regards!

**Comment by sdras** [comment]
Ah, interesting, good to know, thanks!

**Comment by svipben** [comment]
Also, there are new colors from 1.25 version till 1.28 version. I will check them and I will write here full list what need to be removed, fixed or added.

**Comment by sdras** [comment]
fixed!
