### ISSUE TITLE
When showTabs is false tab bar has wrong color

### ISSUE THREAD

**Issue by BrianDGLS** [sdras/night-owl-vscode-theme#99]
When showTabs is false the tab bar has a colour that doesn't match the theme.

Awesome theme, thanks!

Screenshot to demonstrate:
![image](https://user-images.githubusercontent.com/7824734/41748751-183c7652-75ab-11e8-9416-abdd1e4b592a.png)

**Comment by sdras** [comment]
Good point, thanks! I will fix this as soon as I can.

**Comment by robphoenix** [comment]
In the meantime you can fix this in your settings.json file

```
"workbench.colorCustomizations": {
        "[Night Owl]": {
            "editorGroupHeader.noTabsBackground": "#011627"
        },
    },
```
